---
title: "Loneliness Project"
subtitle: "Analyses"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 1: Combine Data  
```{r ipd reg load combined data}
loadRData <- function(fileName, type){
#loads an RData file, and returns it
  print(fileName)
    path <- sprintf("%s/01-data/clean/%s_clean.RData", wd, fileName)
    load(path)
    get(ls()[grepl(type, ls())])
}

nested_data <- tibble(
  study = c("LISS", "SHP", "GSOEP", "SATSA", "HILDA", "OCTOTWIN", "SHARE", "HRS", "ELSA")
  # study = c("SHARE")
  , data = map(str_to_lower(study), ~loadRData(., "comb"))
  ) %>% mutate(
    data = map(data, ~(.) %>% 
                 ungroup() %>% 
                 mutate(SID = as.character(SID)) %>%
                 mutate_at(vars(contains("age")), ~(.)/10))
  ); nested_data

missing_fun <- function(d, study){
  sprintf("NOTE: A total of %s cases in %s have loneliness data and will be included in the final analyses.\n"
          , nrow(d), study)
}
print(map2(nested_data$data, nested_data$study, missing_fun))
```

## Rescale Data  
```{r}
std_vars <- c("b.isolated", "functional", "mstat", "episodic", "educ", "income", "bmi")
pomp <- function(x) (x - min(x, na.rm = T))/(max(x, na.rm = T) - min(x, na.rm = T))*10

nested_data <- nested_data %>%
  mutate(unscaled_data = data
         , data = map(data, ~(.) %>%
                      mutate_at(vars(one_of(std_vars)), ~as.numeric(scale(.))) %>%
                      mutate_at(vars(one_of(std_vars)), ~ifelse(is.nan(.), NA, .)) %>%
                      mutate_at(vars(contains("lonely")), pomp)))
  
```

```{r}
long_fun <- function(d, study){
  #convert dataset to longform
  d <- d %>%
    gather(key = "key", value = "value",
           matches("[0-9]"))  %>%
    filter(!is.na(value)) %>%
    mutate(wave = as.numeric(gsub("[[:alpha:]]", "", key)),
           key = gsub("[[:digit:]]", "", key)) %>%
    spread(key = "key", value = "value")
  
  d <- d %>% 
    mutate(age2 = age * age)
  
  cat(study, "data have been reshaped into long-form. \n")
  return(d)
}

nested_data <- nested_data %>%
  mutate(long_data = map2(data, study, long_fun),
         unscaled_long_data = map2(unscaled_data, study, long_fun),
    meas.oc = map(long_data, ~(.) %>% 
                           group_by(SID) %>%
                           summarize(meas.occ = n()) %>%
                           ungroup()),
    measoccint = map(long_data, ~(.) %>% 
                             select(SID, age, lonely) %>%
                             drop_na() %>%
                             arrange(SID, age) %>%
                             group_by(SID) %>%
                             mutate(diff = (age - lag(age))*10) %>%
                             filter(!is.na(diff)) %>%
                             summarize(measoccint = mean(diff)) %>%
                             ungroup()),
    data = pmap(list(data, meas.oc, measoccint), ~(..1) %>% left_join(..2) %>% left_join(..3))
    )
```


## Descriptives  
```{r}
desc_fun <- function(d, study){
  #calculate descriptives
  other.vars = c("b.isolated", "b.age.yrs", "functional", "sex", "educ", "married"
                 , "divorced", "widowed", "never.married", "income", "bmi", "cc"
                 , "depression", "smoke", "drink", "marital", "episodic", "mstat"
                 , "baseline.year", "last.year", "int", "meas.occ", "measoccint") 
  
  descriptives <- d %>%
    select(one_of(other.vars), contains("lonely")) %>%
    describe(fast=T)
  save(descriptives, file = sprintf("%s/03-results/03-descriptives/%s.RData", wd, study))
  
  cat("Baseline Descriptive statistics for", study, "have been calculated. \n")
  return(descriptives)
}

nested_data <- nested_data %>%
  mutate(desc = map2(data, study, desc_fun))
```

## Zero-Order Correlations  
```{r}
cor_fun <- function(d, study){
  other.vars = c("lonely", "b.age.yrs", "b.isolated", "functional", "sex"
                 , "educ", "married", "divorced", "widowed", "never.married"
                 , "income", "bmi", "cc", "depression", "smoke", "drink"
                 , "episodic", "mstat", "baseline.year") 
  db <- d %>% 
    group_by(SID) %>%
    filter(wave == min(wave)) %>%
    ungroup() %>%
    select(SID, one_of(other.vars))
  
  desc <- db %>%
    pivot_longer(
      cols = -SID
      , values_to = "value"
      , values_drop_na = T
      , names_to = "v1"
    ) %>%
    group_by(v1) %>%
    summarize_at(vars(value), lst(mean, sd)) %>%
    ungroup() %>%
    mutate_at(vars(mean, sd), ~sprintf("%.2f", .))
  
  r <- corr.test(db %>% select(-SID), use = "pairwise") 
  r2 <- apply(r$r, c(1,2), function(x) sprintf("%.2f", x))
  r2[which(r$p < .05, arr.ind = T)] <- sprintf("<strong>%s</strong>", r2[which(r$p < .05, arr.ind = T)])
  
  r2[upper.tri(r2)] <- ""
  diag(r2) <- "--"
  
  r_df <- r2 %>%
    data.frame() %>%
    rownames_to_column("v1") %>%
    # left_join(desc) %>%
    mutate(v1 = paste(seq(1, n()), v1, sep = ". "))
  
  tab <- r_df %>%
    kable(.
          , "html"
          , escape = F
          , caption = sprintf("<strong>Table SX</strong><br><em>Zero-Order Correlations for Baseline Variables in %s", study) #and Descriptives
          , col.names = c("Variable", 1:ncol(r2))#, "M", "SD")
          , align = c("l", rep("c", ncol(r_df) - 1))
          ) %>%
    kable_classic(full_width = F, font_size = 12, html_font = "Times New Roman")
  save_kable(tab, file = sprintf("%s/03-results/10-tables/zero-order-cors/%s.html", wd, study))
  return(tab)
}

nested_data <- nested_data %>%
  mutate(cors = map2(unscaled_long_data, study, cor_fun))
```


## Cross-Sectional Age Differences 

```{r}
stdcolors <- tibble(studies = c("HRS", "SHARE", "ELSA", "SATSA", "OCTOTWIN", "GSOEP", "LISS", "HILDA", "SHP")
       , colors = c("#332288", "#88ccee", "#44aa99", "#117733", "#999933", "#ddcc77", "#cc6677", "#882255", "#aa4499"))

stdcolors$colors

nested_data %>%
  select(study, long_data) %>%
  unnest(long_data) %>%
  filter(!is.na(lonely)) %>%
  group_by(study, SID) %>%
  slice_min(age) %>%
  ungroup() %>%
  mutate(age = round(age)) %>%
  group_by(study, age) %>%
  summarize_at(vars(lonely), lst(mean, sd, n = ~sum(!is.na(.))), na.rm = T) %>%
  ungroup() %>%
  mutate(age = age*10+60
         , se = sd / sqrt(n)
         , lower = mean - se*1.96
         , upper = mean + se*1.96
         , study = factor(study, levels = stdcolors$studies)
         ) %>%
  filter(n > 10 & lower >= 0) %>%
  ggplot(aes(x = age, y = mean, ymin = lower, ymax = upper)) + 
    geom_ribbon(aes(fill = study), alpha = .2) + 
    geom_line(aes(y = upper, color = study)) + 
    geom_line(aes(y = lower, color = study)) + 
    geom_line() + 
    labs(
      x = "Age"
      , y = "Population Average Loneliness (CI)"
      , title = "Cross Sectional Age Differences in Loneliness"
      ) + 
    scale_fill_manual(values = stdcolors$colors)+
    scale_color_manual(values = stdcolors$colors)+
    facet_wrap(~study) + 
    theme_classic() + 
    theme(
      panel.grid.major = element_line()
      , legend.position = "none"
      , strip.text = element_text(face = "bold", color = "white", size = rel(1.1))
      , strip.background = element_rect(fill = "grey40", color = "black")
      , plot.title = element_text(face = "bold", hjust = .5)
      , axis.text = element_text(face = "bold", color = "black", size = rel(1))
      , axis.title = element_text(face = "bold", size = rel(1.1))
    )
ggsave(file = sprintf("%s/03-results/09-plots/cross-sectional-age-differences-cut.png", wd)
       , width = 12, height = 12)
```

```{r}
gam_fun <- function(d){
  d <- d %>%
    select(SID, age, lonely) %>% 
    drop_na() %>%
    group_by(SID) %>%
    filter(n() > 2) %>%
    ungroup() %>%
    mutate(SID = factor(SID))
  m <- mgcv::bam(
    lonely ~ s(age) + s(age, by = SID)
    , method = "REML"
    , data = d
    , nthreads = 12
    )
}
nested_data %>%
  select(study, long_data) 

p <- nested_data %>%
  select(study, long_data) %>%
  unnest(long_data) %>%
  filter(!is.na(lonely)) %>%
  select(study, SID, age, lonely) %>%
  mutate(age2 = round(age)) %>%
  group_by(study, age2) %>%
  mutate_at(vars(lonely), lst(n = ~sum(!is.na(.))), na.rm = T) %>%
  ungroup() %>%
  filter(study == "OCTO" | n > 20) %>%
  mutate(age = age*10 + 60, 
         study = factor(study, levels = stdcolors$studies)) %>%
  ggplot(aes(x = age, y = lonely, group = study)) + 
    geom_smooth(aes(color = study), method = "gam") + 
    facet_wrap(~study) + 
    labs(
      x = "Age"
      , y = "Loneliness (SE)"
      , title = "Age Differences in Loneliness"
      , subtitle = "Estimated using a generalized additive model (GAM)"
      ) + 
    theme_classic() + 
    theme(
      panel.grid.major = element_line()
      , legend.position = "none"
      , strip.text = element_text(face = "bold", color = "white", size = rel(1.1))
      , strip.background = element_rect(fill = "grey40", color = "black")
      , plot.title = element_text(face = "bold", hjust = .5)
      , plot.subtitle = element_text(face = "italic", hjust = .5)
      , axis.text = element_text(face = "bold", color = "black", size = rel(1))
      , axis.title = element_text(face = "bold", size = rel(1.1))
    )
ggsave(p, file = sprintf("%s/03-results/09-plots/gam-age-differences.png", wd)
       , width = 12, height = 12)
```




```{r}
fac_fun <- function(x){
  cols <- colnames(x)[colnames(x) %in% c("drink", "smoke", "depression", "cc")]
  x %>%
    mutate_at(vars(one_of(cols)), as.factor)
}

# update yes/no and count variables to factors (for now)
nested_data <- nested_data %>%
  mutate(data = map(data, fac_fun))
```

## Imputation  
```{r}
mice_call <- function(d, study){
  print(study)
  #do not include these variables as predictors to generate imputed values (we are not including time, outcome, or main effects in the imputation)
  noimp <- c("b.isolated","sex","marital","b.age","functional","educ",
            "married","divorced","widowed","never.married","b.age.yrs", 
            "last.year", "int", "meas.occ", "measoccint")
  sids <- d$SID
  d <- d %>% mutate_if(is.numeric, ~ifelse(is.nan(.) | is.infinite(.), NA, .))
  d2 <- d %>%
    select(-contains("age")
           , -contains("lonely")
           , -one_of(noimp)
           , -one_of("yearBrth")
           , -SID)
  #impute the data
  #mice settings
  init = mice(d2, maxit=0) 
  meth = init$method
  #set method of imputation for each variable type
  meth[names(meth)[names(meth) %in% c("income","bmi","episodic", "mstat")]]="cart" #continuous
  meth[names(meth)[names(meth) %in% c("smoke","drink")]]="logreg" #binary
  meth[c("cc","depression")]="polyreg" #ordinal
  if(study == "OCTOTWIN") meth["cc"] <- "cart"
  #run the imputation
  set.seed(1118)
  imputed <- mice(d2, method=meth, m=5) #impute five times
  
  #convert imputed dataset to long form
  cimp_list <- complete(imputed, action = "all") # gives you a list of imputed sets
  cimp_list <- lapply(cimp_list, function(x) tibble(SID = sids, x))
  # function to make it long
  long_fun <- function(dt){
    dt %>%
      right_join(d %>%
                  select(SID
                         , contains("age")
                         , contains("lonely")
                         , one_of(noimp))
      ) %>%
      gather(key = "key", value = "value",
             matches("[0-9]"))  %>%
      filter(!is.na(value)) %>%
      mutate(wave = as.numeric(gsub("[[:alpha:]]", "", key)),
             key = gsub("[[:digit:]]", "", key)) %>%
      spread(key = "key", value = "value")
  }
  cimp_list_long <- lapply(cimp_list, long_fun)
  
  edit_fun <- function(d){
    d <- d %>%
      mutate(age2=age*age)
    # change these back to numeric
    cols <- colnames(d)[colnames(d) %in% c("drink", "smoke", "depression", "cc")]
    d %>%
      mutate_at(vars(one_of(cols)), ~as.numeric(as.character(.)))
  }
  cimp_list_long <- lapply(cimp_list_long, edit_fun)
}

nested_data <- nested_data %>%
  # filter(!study %in% c("HILDA", "LISS", "GSOEP")) %>%
  mutate(imp = map2(data, study, possibly(mice_call, NA_real_))) %>%
  filter(!is.na(imp))
```

## Data Set Up  

### Wave Requirements  
```{r}
nested_data %>% 
  select(-data, -desc) %>%
  mutate(nw = map(long_data, ~(.) %>% 
                    group_by(SID) %>% 
                    tally() %>% 
                    group_by(n) %>% 
                    tally() %>% 
                    ungroup())) %>%
  unnest(nw) %>%
  select(-long_data) %>%
  pivot_wider(names_from = n, values_from = nn)
```


## Models  
### Functions  
#### Options  
```{r}
#LMER Control Settings
  nlopt <- function(par, fn, lower, upper, control) {
    .nloptr <<- res <- nloptr(par, fn, lb = lower, ub = upper,
                              opts = list(algorithm = "Nelder_Mead", print_level = 1,
                                          maxeval = 1000, xtol_abs = 1e-6, ftol_abs = 1e-6))
    list(par = res$solution, fval = res$objective, conv = if (res$status > 0) 0 else res$status,
         message = res$message)
  }
```

#### Model Call  
```{r}
lmer_call <- function(d, f){
  lonely.intercept <- lmer(formula(f)
                           , data = d
                           , REML=F
                           , control = lmerControl(optimizer = Nelder_Mead
                                                   , calc.derivs = FALSE)
                           )
}
```

#### Model Predictions (Simple Effects)
```{r}
pred_fun <- function(m, int, mod, cov){
  if(mod == "unconditional") return(NA)
  
  std_int <- c("b.isolated", "functional", "mstat", "episodic", "educ", "bmi", "income")
  std_int <- std_int[std_int %in% colnames(m@frame)]
  fac_int <- c("sex", "marital", "smoke", "drink", "cc", "depression")
  
  dsc <- describe(m@frame, fast = T) %>% as.data.frame()
  frame <- tibble(age = seq(dsc["age", "min"], dsc["age", "max"], length.out = 50)
      , SID = "999999999")
  # deal with quadratic models
  if(mod == "Quadratic"){
    frame <- frame %>% mutate(age2 = age^2)
  }
  std_int <- std_int[std_int %in% names(m@frame)]
  # deal with interaction terms
  if(grepl("Interaction", int)){
    # add in standardized vars
    for (i in 1:length(std_int)) {
      frame <- crossing(frame, X = c(-1,1)); colnames(frame)[ncol(frame)] <- std_int[i]
    }
      frame <- crossing(
        frame
        , b.age = c(-1.5, 1.5)
        , marital = c("A", "B", "C", "D")
        , sex = c(0, 1)
      )
  } 
  
  if(int == "AllInteraction"){
    frame <- crossing(
      frame
      , smoke = c(0, 1)
      , drink = c(0, 1)
      , cc = c(0, 1)
      , depression = c(0, 1)
    )
  }
  
  if(int == "b.age"){
    # add in standardized vars
    for (i in 1:length(std_int)) {
      frame <- crossing(frame, X = c(-1,1)); colnames(frame)[ncol(frame)] <- std_int[i]
    }
      frame <- crossing(
        frame
        , b.age = c(-4,-2,0)
        , marital = c("A", "B", "C", "D")
        , sex = c(0, 1)
      )
  }
  if(cov == "adj") { # and covariates
    # add in numeric
    frame <- data.frame(
      m@frame %>% 
        select(-one_of(colnames(frame)), -SID) %>%
        summarize_if(is.numeric, mean) 
      , frame)
    
    # add in factors 
    if(any(colnames(m@frame) %in% colnames(frame) == F)){
      cols <- colnames(m@frame)[!colnames(m@frame) %in% colnames(frame)]
      for (i in 1:sum(colnames(m@frame) %in% colnames(frame) == F)){
        levs <- levels(m@frame[,cols[i]])
        frame <- crossing(frame, X = levs); colnames(frame)[ncol(frame)] <- cols[i]
      }
    }
  }
  
  pred_int_fun <- function(df, age){
    pred <- df %>%
      mutate(age = age) %>%
    bind_cols(
      .
      , predictInterval(
        merMod = m
        , newdata = .
        , n.sims = 500
        , include.resid.var = F
      )) %>%
    mutate(fit = predict(m, newdata = ., re.form = NA, allow.new.levels = T)) %>%
      select(-age)
    return(pred)
  }
  
  # get model based predictions
  frame <- frame %>%
  
    bind_cols(
      .
      , predictInterval(
        merMod = m
        , newdata = .
        , .parallel = T
        , include.resid.var = F
      )) %>%
    mutate(fit = predict(m, newdata = ., re.form = NA, allow.new.levels = T))
  return(frame)
}
```

#### Baseline Age Interactions  

```{r}
simple_eff_fun <- function(m){
  mes <- c("b.isolated", "sex", "maritalB", "maritalC", "maritalD", "b.age", "functional", "educ")
  mes <- mes[mes %in% names(fixef(m)) & mes != "b.age"]
  contr.fun <- function(me){
    x1 <- sapply(me, function(x) sprintf("%s + -4*b.age:%s = 0", x, x))
    x2 <- sapply(me, function(x) sprintf("%s + -2*b.age:%s = 0", x, x))
    x3 <- sapply(me, function(x) sprintf("%s = 0", x))
    names(x1) <- paste0("age20-", names(x1))
    names(x2) <- paste0("age40-", names(x2))
    names(x3) <- paste0("age60-", names(x3))
    c(x1, x2, x3)
  }
  
  cntrm <- contr.fun(mes)
  (multcomp::glht(m, linfct = cntrm) %>% # multcomp hypothesis function
    confint(., calpha = multcomp::univariate_calpha()))$confint %>%
    data.frame() %>% 
    rownames_to_column("cntr") %>%
    mutate(term = names(cntrm)) %>% 
    select(-cntr) %>%
  mutate(est = sprintf("b = %.2f, 95%% CI [%.2f, %.2f]", Estimate, lwr, upr))
}
```


#### Model Coefficients  
```{r}
summary_fun <- function(m, pool = NULL, mlist_pool = NULL, plot = NULL, imp){
  res <- if(imp == "unimp"){
    list(
          coef = coef(summary(m)) %>% data.frame %>% rownames_to_column("term") %>% setNames(c("term", "estimate", "std.error", "t.value")),
          rand = as.data.frame(VarCorr(m)),
          icc = performance::icc(m),
          ll = summary(m)[["logLik"]],
          n.group = summary(m)[["ngrps"]],
          n.obs = nrow(m@frame)
        )
  } else {
    list(
        coef = summary(pool),
        rand_e = as.data.frame(mlist_pool$errorList),
        rand_c = as.data.frame(mlist_pool$corrList),
        rand_r = as.data.frame(mlist_pool$residError),
        # icc = performance::icc(lonely.quadfinaladj),
        ll_r = range(sapply(m, function(x) summary(x)[["logLik"]])),
        ll_m = median(sapply(m, function(x) summary(x)[["logLik"]])),
        n.group = summary(m$'1')[["ngrps"]],
        n.obs = pool$glanced$nobs[1]
      )
  }
  if(!is.null(plot)) res$plot = plot
  return(res)
}
```

#### Results Object  
```{r, eval = F}
loadRData <- function(fileName, type, pt){
#loads an RData file, and returns it
  print(fileName)
    path <- sprintf("%s/03-results/%s/%s", wd, pt, fileName)
    load(path)
    get(ls()[ls() == "m"])
}

sum_save <- function(file, int, model, cov){
  m <- loadRData(file, "m", "01-models")
  pl <- loadRData(file, "m", "06-pooled")
  mlist <- loadRData(file, "m", "01-models/01-model-lists")
  mlist_pool <- summary(mlist)
  m1 <- m[[1]]
  m1@beta <- summary(pl)$estimate
  pred <- pred_fun(m1, int, model, cov)
  summ <- summary_fun(m, pool = pl, mlist_pool = mlist_pool, imp = "Imputed", plot = pred)
  m <- summ
  save(m, file = sprintf("%s/03-results/04-summary/%s"
                            , wd, file))
  m <- pred
  save(m, file = sprintf("%s/03-results/02-predicted/%s"
                            , wd, file))
  return(T)
}

library(httr)
list_files_github <- function(){
  req <- GET("https://api.github.com/repos/emoriebeck/loneliness-trajectories/git/trees/master?recursive=1")
  stop_for_status(req)
  filelist <- unlist(lapply(content(req)$tree, "[", "path"), use.names = F)
  grep("03-results/04-summary/", filelist, value = TRUE, fixed = TRUE)
}

nested_res <- tibble(
  file = list_files_github() %>% str_remove_all(., "03-results/04-summary/")
) %>%
  separate(file, c("Imputed", "study", "model", "random", "int", "cov"), sep = "_", remove = F) %>% 
  filter(Imputed == "imp" & int != "Intteraction") %>%
  mutate(cov = str_remove_all(cov, ".RData")
         , save = pmap(list(file, int, model, cov)
                              , .f = sum_save
                              ))
```


#### Unimputed Model Setup 
```{r}
lmer_fun <- function(d, study){
  mes <- c("b.isolated", "sex", "marital", "b.age", "functional", "educ")
  mes <- mes[mes %in% colnames(d)]
  mes2 <- mes[mes %in% colnames(d) & mes != "b.age"]
  ints2 <- paste("b.age", mes2, sep = "*")
  ints <- paste("age", mes, sep = "*")
  qints <- str_replace_all(ints, "[*]", "2*")
  
  d <- d %>% group_by(SID) %>% filter(n() > 2) %>% ungroup() 
  
  # plan(multisession(workers = 9L))
  nested_models <- tribble(
    ~model          , ~random      ,~int           , ~cov   , ~form ,
    "unconditional" , "intercept"  , "Main"        , "none" , "lonely ~ (1 | SID)", # 1
    "Linear"        , "intercept"  , "Main"        , "none" , "lonely ~ age + (1 | SID)", # 2
    "Linear"        , "slope"      , "Main"        , "none" , "lonely ~ age + (1 + age | SID)", # 3
    "Linear"        , "slope"      , "Main"        , "adj"  ,  paste0("lonely ~ ", paste0(c("age", mes), collapse = " + "), " + (1 + age | SID)"), # 4
    "Quadratic"     , "intercept"  , "Main"        , "none" , "lonely ~ age + age2 + (1 | SID)", # 8
    "Quadratic"     , "slope"      , "Main"        , "none" , "lonely ~ age + age2 + (1 + age + age2 | SID)", # 9
    "Linear"        , "slope"      , "Main"        , "adj"  ,  paste0("lonely ~ ", paste0(c("age", mes), collapse = " + "), " + (1 + age | SID)"), # 10
    "Linear"        , "slope"      , "Interaction" , "adj"  ,  paste0("lonely ~ ", paste0(c("age", ints), collapse = " + "), " + (1 + age | SID)"), # 6
    "Quadratic"     , "slope"      , "Interaction" , "adj"  ,  paste0("lonely ~ ", paste0(c("age", ints, qints), collapse = " + "), " + (1 + age | SID)"), # 12
    "Linear"        , "slope"      , "b.age"       , "adj"  ,  paste0("lonely ~ ", paste0(c("age", ints2), collapse = " + "), " + (1 + age | SID)"),
    "Quadratic"     , "slope"      , "b.age"       , "adj"  ,  paste0("lonely ~ ", paste0(c("age", "age2", ints2), collapse = " + "), " + (1 + age | SID)")
  ) %>%
    # filter(int == "b.age") %>%
    mutate(data = map(model, function(x) if(x == "Linear") d else d %>% group_by(SID) %>% filter(n() > 3) %>% ungroup())
           , m = map(form,  possibly(~lmer_call(d,.), NA_real_))
           , pred = pmap(list(m, int, model, cov), possibly(pred_fun, NA_real_))
           , res = map(m, possibly(~summary_fun(m = ., imp = "unimp"), NA_real_)))
  closeAllConnections()
  
  save_fun <- function(md, study, r, i, cv, m, imp, res) {
    if(all(md == "unconditional" & res == "02-predicted") == F){
      save(m
           , file = sprintf("%s/03-results/%s/%s_%s_%s_%s_%s_%s.RData"
                            , wd, res, imp, study, md, r, i, cv)
           )
    } else return(NA_real_)
  }
  nested_models %>% mutate(s = pmap(list(model, study, random, int, cov, m, "unimp", "01-models"),  possibly(save_fun, NA_real_)),
                           p = pmap(list(model, study, random, int, cov, pred, "unimp", "02-predicted"),  possibly(save_fun, NA_real_)),
                           s = pmap(list(model, study, random, int, cov, res, "unimp", "04-summary"),  possibly(save_fun, NA_real_)))
  return(T)
}

nested_unimp <- nested_data %>%
  # filter(study %in% c("OCTOTWIN")) %>%
  select(-data, -desc, -imp) %>%
  mutate(m = map2(long_data, study, lmer_fun))
```

#### Imputed Model Setup
```{r}
lmer_imp_fun <- function(dl, study){
  # set up terms and formulas
  mes <- c("b.isolated", "sex", "marital", "b.age", "functional", "educ", "income"
           , "drink", "smoke", "bmi", "cc", "depression", "episodic", "mstat")
  mes         <- mes[mes %in% colnames(dl[[1]])]
  mint        <- paste("age", c("b.isolated", "sex", "marital", "b.age", "functional", "educ"), sep = "*")
  allmint     <- paste("age", mes, sep = "*")
  mint2       <- paste("b.age", mes[mes!= "b.age"], sep = "*")
  mintq       <- str_replace_all(mint, "[*]", "2*")
  allmintq    <- str_replace_all(allmint, "[*]", "2*")
  mintq2      <- paste("b.age", mes[mes!= "b.age"], sep = "*")
  # formulas
  flin        <- paste0("lonely ~ ", paste0(c("age", mes)              , collapse = " + "), " + (1 + age | SID)")
  fquad       <- paste0("lonely ~ ", paste0(c("age", "age2", mes)      , collapse = " + "), " + (1 + age + age2 | SID)")
  fint        <- paste0("lonely ~ ", paste0(c("age", mes, mint)        , collapse = " + "), " + (1 + age | SID)")
  fintall     <- paste0("lonely ~ ", paste0(c("age", allmint)          , collapse = " + "), " + (1 + age | SID)")
  fquadint    <- paste0("lonely ~ ", paste0(c("age", mes, mint, mintq) , collapse = " + "), " + (1 + age + age2 | SID)")
  fquadintall <- paste0("lonely ~ ", paste0(c("age", allmint, allmintq), collapse = " + "), " + (1 + age + age2 | SID)")
  fint2       <- paste0("lonely ~ ", paste0(c("age", mint2)            , collapse = " + "), " + (1 + age | SID)")
  fquadint2   <- paste0("lonely ~ ", paste0(c("age", "age2", mintq2)   , collapse = " + "), " + (1 + age + age2 | SID)")
  
  dl <- map(dl, ~(.) %>% 
              group_by(SID) %>% 
              filter(n() > 2) %>% 
              ungroup() %>%
              mutate(marital = fct_drop(marital)))
              # mutate(marital = ifelse(!marital %in% c("A", "B", "C", "D"), NA, marital))
  
  save_fun <- function(md, study, r, i, cv, m, imp, res) {
    if(all(md == "unconditional" & res == "02-predicted") == F){
      save(m
           , file = sprintf("%s/03-results/%s/%s_%s_%s_%s_%s_%s.RData"
                            , wd, res, imp, study, md, r, i, cv)
           )
    } else return(NA_real_)
  }
  
  # plan(multisession(workers = 4L))
  nested_imp <- tribble(
    ~model     , ~random , ~int             , ~cov  , ~form,
    "Linear"   , "slope" , "Main"           , "adj" , flin, # 5
    "Quadratic", "slope" , "Main"           , "adj" , fquad, # 11
    "Linear"   , "slope" , "Interaction"    , "adj" , fint, # 7
    "Quadratic", "slope" , "Interaction"    , "adj" , fquadint, # 13
    "Linear"   , "slope" , "AllInteraction" , "adj" , fintall, # 7
    "Quadratic", "slope" , "AllInteraction" , "adj" , fquadintall, # 13
    "Linear"   , "slope" , "b.age"          , "adj" , fint2, # 7
    "Quadratic", "slope" , "b.age"          , "adj" , fquadint2 
  ) %>%
    # filter(int == "AllInteraction") %>%
    mutate(
      # run the models
      m            = map(form , possibly(~lapply(dl, function(x) lmer_call(x, .)), NA_real_))
      , s = pmap(list(model, study, random, int, cov, m, "imp", "01-models"), possibly(save_fun, NA_real_))
      
      # pool the models
      , pool       = map(m    , possibly(mice::pool, NA_real_))
      , s = pmap(list(model, study, random, int, cov, pool, "imp", "06-pooled"), possibly(save_fun, NA_real_))
      
      # get pooled random effects
      , mlist      = map(form    , possibly(~lmerModList(., data = dl), NA_real_))
      , s = pmap(list(model, study, random, int, cov, mlist, "imp", "01-models/01-model-lists"), possibly(save_fun, NA_real_))
      
      , mlist_pool = map(mlist   , possibly(summary, NA_real_))
      
      # get pooled predictions
      , m1 = map(m, possibly(~(.)[[1]], NA_real_))
      , m1 = map2(m1, pool, possibly(function(x,y) {x@beta <- summary(y)$estimate; return(x)}, NA_real_))
      , mplot      = pmap(list(m1, int, model, cov), possibly(pred_fun, NA_real_))
      , s = pmap(list(model, study, random, int, cov, mplot, "imp", "02-predicted"), possibly(save_fun, NA_real_))
      
      # get results object
      , res = pmap(list(m, pool, mlist_pool, mplot, "imp"), possibly(summary_fun, NA_real_))
      , s = pmap(list(model, study, random, int, cov, res, "imp", "04-summary"), possibly(save_fun, NA_real_))
      )
  # closeAllConnections()
  return(T)
}

plan(multisession(workers = 8L))
nested_imp_mods <- nested_data %>%
  mutate(m = 
           future_map2(imp, study
           # map2(imp, study
                         , .f = lmer_imp_fun
                         , .progress = T
    , .options = furrr_options(
          globals = c("lmer_fun"
                      , "lmer_call"
                      , "long_fun"
                      , "pred_fun"
                      , "comp_fun"
                      , "psych"
                      , "wd"
                      , "nlopt"
                      , "summary_fun"
                      , "fac_fun")
        , packages = c("lme4"
                       , "broom"
                       , "broom.mixed"
                       , "mice"
                       , "merTools"
                       , "plyr"
                       , "tidyverse"))
    ))
closeAllConnections()
```

```{r}
se_fun <- function(file){
  load(sprintf("%s/03-results/01-models/%s", wd, file))
  if(grepl("^imp", file)){
    mp <- mice::pool(m)
    m1 <- m[[1]]
    m1@beta <- summary(mp)$estimate
  } else {
    m1 <- m
  }
  se <- simple_eff_fun(m1)
  save(se, file = sprintf("%s/03-results/11-b.age-int-slopes/%s"
                          , wd, file))
}

tibble(file = list.files(sprintf("%s/03-results/01-models", wd), pattern = "b.age_adj.RData")) %>%
  filter(grepl("^unimp", file)) %>%
  mutate(se = map(file, se_fun))
```

## Compile ICC's    

```{r}
loadRData <- function(fileName){
#loads an RData file, and returns it
  print(fileName)
    path <- sprintf("%s/03-results/04-summary/%s", wd, fileName)
    load(path)
    get(ls()[ls() == "m"])
    res <- tibble(out = names(m), data = m) %>%
      pivot_wider(names_from = "out", values_from = "data")
}

nested_res <- tibble(
  file = sprintf("%s/03-results/04-summary", wd) %>% list.files()
) %>%
  separate(file, c("Imputed", "study", "model", "random", "int", "cov"), sep = "_", remove = F) %>% 
  filter(model == "unconditional") %>%
  mutate(data = map(file, loadRData)
         , cov = str_remove_all(cov, ".RData")) %>%
  unnest(data)

nested_res %>% 
  select(Imputed:cov, icc) %>% 
  mutate(icc = map_dbl(icc, ~(.)$ICC_conditional)) %>%
  select(study, icc)
```

