---
title: "03-meta-analysis"
author: "Emorie Beck"
date: "9/16/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
stdcolors <- tibble(studies = c("HRS", "SHARE", "ELSA", "SATSA", "OCTOTWIN", "GSOEP", "LISS", "HILDA", "SHP")
       , colors = c("#332288", "#88ccee", "#44aa99", "#117733", "#999933", "#ddcc77", "#cc6677", "#882255", "#aa4499"))
```

# Descriptives  
```{r}
loadRData <- function(fileName){
#loads an RData file, and returns it
    path <- sprintf("%s/03-results/03-descriptives/%s.RData", wd, fileName)
    print(path)
    load(path)
    get(ls()[ls() == "descriptives"])
    descriptives %>% as.data.frame() %>% rownames_to_column("variable")
}

nested_desc <- tibble(
  study = studies
) %>%
  mutate(data = map(study, loadRData)
         , study = str_remove_all(study, ".RData")) %>%
  unnest(data) %>%
  select(study, variable, n, mean, sd, min, max, range) %>%
  arrange(study, variable)

rs <- nested_desc %>% group_by(study) %>% tally() %>% 
    mutate(end = cumsum(n), start = lag(end) + 1, start = ifelse(is.na(start), 1, start))

desc_tab <- nested_desc %>%
  select(-study) %>%
  mutate(variable = str_replace_all(variable, "_", "")) %>%
  kable(.
        ,  booktabs = T
        , escape = FALSE
        , digits = 2
        , format = "html"
        , longtable=T
        , col.names = c("Variable", "N Valid", "Mean", "SD", "Min", "Max", "Range")
        , caption = "Descriptive Statistics") %>%
  kable_classic(full_width = F, font_size = 12, html_font = "Times New Roman") %>%
  add_footnote("add necessary notes", notation="alphabet")

for (i in 1:nrow(rs)) {
  desc_tab <- desc_tab %>% 
    kableExtra::group_rows(rs$study[i], rs$start[i], rs$end[i])
}
desc_tab
```


```{r}
std.meta <- tribble(
  ~study,          ~country,            ~scale
  , "LISS"         , "The Netherlands"  , "CES-D"
  , "GSOEP"        , "Germany"          , "CES-D"
  , "HILDA"        , "Australia"        , "CES-D"
  , "SHP"          , "Switzerland"      , "CES-D"
  , "SATSA"        , "Sweden"           , "CES-D"
  , "OCTOTWIN"     , "Sweden"           , "CES-D"
  , "HRS"          , "United States"    , "UCLA"
  , "SHARE"        , "Europe"           , "UCLA"
  , "ELSA"         , "United Kingdom"   , "UCLA"
)

vars <- tribble(
  ~old,            ~new
  , "country"      , "Country"
  , "scale"        , "Loneliness Scale"
  , "b.isolated"   , "Baseline Social Isolation M (SD)"
  , "functional"   , "Functional Limitations M (SD)"
  , "educ"         , "Years of Education M (SD)"
  , "baseline.year", "Year of First Measurement M (SD)"
  , "last.year"    , "Year of Last Measurement M (SD)"
  , "int"          , "Measurement Interval (Years) M (SD)"
  , "lonely1"      , "Baseline Loneliness M (SD)"
  , "b.age.yrs"    , "Baseline Age (Years) M (range)"
  , "meas.occ"     , "Measurement Occasions M (range)"
  , "sex"          , "\\% Female"
  , "married"      , "\\% Married"
  , "divorced"     , "\\% Divorced"
  , "widowed"      , "\\% Widowed"
  , "never.married", "\\% Never Married"
  , "baseline.n"   , "Baseline N"
)

man_desc_tab <- std.meta %>% 
  pivot_longer(names_to = "variable", values_to = "value", cols = c(country, scale)) %>%
  pivot_wider(names_from = "study", values_from = "value") %>%
  full_join(
    nested_desc %>%
      filter(variable %in% c("b.isolated", "educ", "functional", "lonely1", "baseline.year", "last.year", "int")) %>%
      mutate(est = sprintf("%.2f (%.2f)", mean, sd)) %>%
      select(study, variable, est) %>%
      pivot_wider(names_from = "study"
                  , values_from = "est")
  ) %>% full_join(
    nested_desc %>%
      filter(variable %in% c("b.age.yrs")) %>%
      mutate_at(vars(mean, min, max), ~(.)*10) %>%
      mutate(est = sprintf("%.1f (%.0f-%.0f)", mean, min, max)) %>%
      select(study, variable, est) %>%
      pivot_wider(names_from = "study"
                  , values_from = "est")
  ) %>% full_join(
    nested_desc %>%
      filter(variable %in% c("meas.occ")) %>%
      mutate(est = sprintf("%.1f (%.0f-%.0f)", mean, min, max)) %>%
      select(study, variable, est) %>%
      pivot_wider(names_from = "study"
                  , values_from = "est")
  ) %>% full_join(
    nested_desc %>%
      filter(variable %in% c("married", "divorced", "widowed", "never.married", "sex")) %>%
      mutate(est = sprintf("%.1f%%", mean*100)) %>%
      select(study, variable, est) %>%
      pivot_wider(names_from = "study"
                  , values_from = "est")
  ) %>% full_join(
    nested_desc %>% 
      filter(variable == "lonely1") %>%
      select(study, baseline.n = n) %>%
      pivot_wider(names_from = "study", values_from = "baseline.n") %>%
      mutate(variable = "baseline.n") %>%
      mutate_all(as.character)
  ) %>%
  mutate(variable = factor(variable, vars$old, vars$new)) %>%
  rename(`OCTO-TWIN` = OCTOTWIN, Variable = variable)
save(man_desc_tab, file = sprintf("%s/03-results/man_desc_tab.RData", wd))

man_desc_tab <- man_desc_tab %>%
  kable(.
        , "html"
        , booktabs = T
        , align = c("r", rep("c", 9))
        , caption = "Descriptive Statistics Across Studies") %>%
  kable_classic(full_width = F, font_size = 12, html_font = "Times New Roman"); man_desc_tab
save_kable(man_desc_tab, file = sprintf("%s/03-results/10-tables/study-desc-tab.html", wd))
```


```{r}
link_fun <- function(d, int){
  if(!int %in% c("continent", "scale")){
    d <- d %>% mutate(metamod = as.numeric(metamod))
  }
  return(d)
}

study.info <- tibble(
  study=c('ELSA','GSOEP','HILDA','HRS','LISS','OCTOTWIN','SATSA','SHARE','SHP'),
  continent=c("Europe", "Europe", "Australia", "United States", "Europe", "Europe", "Europe", "Europe", "Europe"),
  year=c('2004','1990','2006','2009','2009','1991','1985','2004','2019'),
  lastYear = c('2016', '2018', '2019', '2016', '2020', '2000', '2007', '2012', '2020'),
  MO=c('7','20','13','5','12','5','9','4','14'),
  interval=c('2','1','1','2','1','2','3','2','1'),
  scale=c('UCLA','CES-D','CES-D','UCLA','Rasch-Type','CES-D','CES-D','UCLA','CES-D'),
  range = as.character(as.numeric(lastYear)-as.numeric(year))
) %>%
  select(-lastYear) %>%
  pivot_longer(
    cols = -study
    , names_to = "int"
    , values_to = "metamod"
  ) %>%
    group_by(int) %>%
    nest() %>%
    ungroup() %>%
    mutate(data = map2(data, int, link_fun))
```

# Compile Results  
```{r}
loadRData <- function(fileName){
#loads an RData file, and returns it
  print(fileName)
    path <- sprintf("%s/03-results/04-summary/%s", wd, fileName)
    load(path)
    get(ls()[ls() == "m"])
    res <- tibble(out = names(m), data = m) %>%
      pivot_wider(names_from = "out", values_from = "data")
}

nested_res <- tibble(
  file = sprintf("%s/03-results/04-summary", wd) %>% list.files()
) %>%
  separate(file, c("Imputed", "study", "model", "random", "int", "cov"), sep = "_", remove = F) %>% 
  # filter(int == "AllInteraction") %>%
  mutate(data = map(file, possibly(loadRData, NA_real_))
         , cov = str_remove_all(cov, ".RData")) %>%
  select(-file) %>%
  filter(!is.na(data)) %>%
  filter(study != "BHPS") %>%
  filter(!(study == "OCTOTWIN" & model == "Quadratic" & grepl("Interaction", int))) %>%
  # filter(int == "b.age") %>%
  unnest(data)
```

# Study Results  
## Fixed Effect Tables  
```{r}
terms <- tribble(
  ~old                    , ~new
  , "(Intercept)"           , "(Intercept)"
  , "age"                 , "Age"
  , "age2"                , "Age^2"
  , "b.age"               , "Baseline Age"
  , "sex"                 , "Sex"
  , "b.isolated"          , "Social Isolation"
  , "functional"          , "Functional Limitations"
  , "maritalB"            , "Divorced (v. Married)"
  , "maritalC"            , "Widow (v. Married)"
  , "maritalD"            , "Never Married (v. Married)"
  , "educ"                , "Education"
  , "income"              , "Income"
  , "drink1"              , "Drinker"
  , "drink"               , "Drinker"
  , "smoke1"              , "Smoker"
  , "smoke"               , "Smoker"
  , "bmi"                 , "BMI"
  , "cc1"                 , "Conditions (1)"
  , "cc2"                 , "Conditions (2)"
  , "cc3"                 , "Conditions (3)"
  , "cc"                  , "Conditions"
  , "depression1"         , "Depression"
  , "depression"          , "Depression"
  , "episodic"            , "Episodic Memory"
  , "mstat"               , "Mental Status"
  , "age:b.age"           , "Age x Baseline Age"
  , "age:sex"             , "Age x Sex"
  , "age:b.isolated"      , "Age x Social Isolation"
  , "age:functional"      , "Age x Functional Limitations"
  , "age:maritalB"        , "Age x Divorced (v. Married)"
  , "age:maritalC"        , "Age x Widow (v. Married)"
  , "age:maritalD"        , "Age x Never Married (v. Married)"
  , "age:educ"            , "Age x Education"
  , "age:income"          , "Age x Income"
  , "age:drink1"          , "Age x Drinker"
  , "age:drink"           , "Age x Drinker"
  , "age:smoke1"          , "Age x Smoker"
  , "age:smoke"           , "Age x Smoker"
  , "age:bmi"             , "Age x BMI"
  , "age:cc1"             , "Age x Conditions (1)"
  , "age:cc2"             , "Age x Conditions (2)"
  , "age:cc3"             , "Age x Conditions (3)"
  , "age:cc"              , "Age x Conditions"
  , "age:depression1"     , "Age x Depression"
  , "age:depression"      , "Age x Depression"
  , "age:episodic"        , "Age x Episodic Memory"
  , "age:mstat"           , "Age x Mental Status"
  , "b.age:sex"           , "Baseline Age x Sex"
  , "b.age:b.isolated"    , "Baseline Age x Social Isolation"
  , "b.age:functional"    , "Baseline Age x Functional Limitations"
  , "b.age:maritalB"      , "Baseline Age x Divorced (v. Married)"
  , "b.age:maritalC"      , "Baseline Age x Widow (v. Married)"
  , "b.age:maritalD"      , "Baseline Age x Never Married (v. Married)"
  , "b.age:educ"          , "Baseline Age x Education"
  , "b.age:age2"          , "Age^2 x Baseline Age"
  , "sex:age2"            , "Age^2 x Sex"
  , "b.isolated:age2"     , "Age^2 x Social Isolation"
  , "functional:age2"     , "Age^2 x Functional Limitations"
  , "maritalB:age2"       , "Age^2 x Divorced (v. Married)"
  , "maritalC:age2"       , "Age^2 x Widow (v. Married)"
  , "maritalD:age2"       , "Age^2 x Never Married (v. Married)"
  , "educ:age2"           , "Age^2 x Education"
  , "income:age2"         , "Age^2 x Income"
  , "drink1:age2"         , "Age^2 x Drinker"
  , "drink:age2"          , "Age^2 x Drinker"
  , "smoke1:age2"         , "Age^2 x Smoker"
  , "smoke:age2"          , "Age^2 x Smoker"
  , "bmi:age2"            , "Age^2 x BMI"
  , "cc1:age2"            , "Age^2 x Conditions (1)"
  , "cc2:age2"            , "Age^2 x Conditions (2)"
  , "cc3:age2"            , "Age^2 x Conditions (3)"
  , "cc:age2"             , "Age^2 x Conditions"
  , "depression1:age2"    , "Age^2 x Depression"
  , "depression:age2"     , "Age^2 x Depression"
  , "episodic:age2"       , "Age^2 x Episodic Memory"
  , "mstat:age2"          , "Age^2 x Mental Status"
  , "metamodEurope"       , "Australia v Europe"
  , "metamodUnited States", "Australia v United States"
  , "metamodRasch-Type"   , "CES-D v Rasch-Type Scale"
  , "metamodUCLA"         , "CES-D v UCLA Scale"
  , "Int Var"             , "\\\\tau_{00}$"
  , "Slope Var"           , "$\\\\tau_{11}$ \n"
  , "Q Slope Var"         , "$\\\\tau_{22}$ \n"
  , "Int-Slope Covar"     , "$\\\\tau_{01}$ \n"
  , "Residual"            , "$\\\\sigma^2$"
  # , "icc",    
  , "n.group"             , "$N_{people}$"
  , "n.obs"               , "$N_{obs}$"
  , "ll"                  , "LL"
)
                         

stdy_tab_fun <- function(imp, mod, rand, int, cov, d){
  ncols <- (ncol(d)-2)
  stdys <- unique(sapply(str_split(colnames(d)[-c(1:2)], pattern = "_"), function(x) x[[1]]))
  hdr <- c(1, rep(2, times = length(stdys))); names(hdr) <- c(" ", stdys)
  rs <- d %>% group_by(type) %>% tally() %>% 
    mutate(end = cumsum(n), start = lag(end) + 1, start = ifelse(is.na(start), 1, start))
  cap <- if(mod == "unconditional") "Unconditional" else sprintf("Loneliness-%s model", mod)
  cap <- paste(cap, if(grepl("Interaction", int)) "with Predictor Main Effects and Interactions" else "with Predictor Main Effects") 
  cap <- paste(if(cov == "adj") "Covariate Adjusted" else "Unadjusted", cap)
  tab <- d %>%
    select(-type) %>%
    kable(.
          , "html"
          , escape = F
          , booktabs = T
          , col.names = c("Term", rep(c("b (SE)", "p"), times = ncols/2))
          , align = c("r", rep("c", ncols))
          , caption = cap
          ) %>%
    kable_classic(full_width = F, font_size = 12, html_font = "Times New Roman") %>%
    add_header_above(hdr) %>%
    add_footnote("LL = Log Likelihood; Age = age (centered at 60).", notation="alphabet")
  for(i in 1:nrow(rs)){
    tab <- tab %>% kableExtra::group_rows(rs$type[i], rs$start[i], rs$end[i])
  }
  save_kable(tab, file = sprintf("%s/03-results/10-tables/study-summaries/%s_%s_%s_%s_%s.html", wd, imp, mod, rand, int, cov))
  return(tab)
}

### tau / random effects
nested_tau <- nested_res %>%
  mutate(rand_r = map(rand_r, ~unname(as.numeric(unclass(.))))) %>%
  unnest(rand_r) %>%
  unnest(n.obs) %>%
  unnest(n.group) %>%
  unnest(ll_m) %>%
  mutate(rand_c = map_dbl(rand_c, ~(.)[2,1])
         , rand_e = map(rand_e, ~(.) %>% 
                data.frame %>% 
                rownames_to_column("var") %>%
                mutate(var = mapvalues(var, c("(Intercept)", "age", "age2"), 
                                       c("Int Var", "Slope Var", "Q Slope Var"))) %>%
                pivot_wider(names_from = var, values_from = SID))) %>%
  unnest(rand_e) %>%
  select(Imputed:cov, `Int Var`, `Slope Var`, `Q Slope Var`, `Int-Slope Covar` = rand_c, Residual = rand_r
         , n.obs, n.group = n.group, ll = ll_m) %>%
  pivot_longer(cols = c(`Int Var`, `Slope Var`, `Q Slope Var`, `Int-Slope Covar`, Residual, n.obs, n.group, ll)
               , names_to = "term"
               , values_to = "value"
               , values_drop_na = T) %>%
  mutate(stat = "bse"
         , value = value^2
         , value = ifelse(abs(value) < .01 & !term %in% c("n.obs", "n.group"), sprintf("%.3f", value), ifelse(term %in% c("n.obs", "n.group"), as.character(value), sprintf("%.2f", value)))
         , type = ifelse(term %in% c("n.obs", "n.group", "ll"), " ", "Random"))

nested_study_tabs <- nested_res %>%
  select(Imputed:cov, coef) %>%
  unnest(coef) %>%
  filter(!is.na(term)) %>%
  mutate(pval = pnorm(abs(estimate/`std.error`), lower.tail = FALSE)
         , p = ifelse(pval < .001, "&lt; .001", sprintf("%.2f", pval))
         , type = "Fixed") %>%
  mutate_at(vars(estimate, std.error), ~ifelse(abs(.) < .01, sprintf("%.3f", .), sprintf("%.2f", .))) %>%
  mutate(bse = sprintf("%s<br>(%s)", estimate, std.error)) %>%
  select(Imputed, model, random, int, cov, type, bse, p, term, study) %>%
  pivot_longer(cols = c(bse, p)
               , names_to = "stat"
               , values_to = "value") %>%
  full_join(nested_tau) %>%
  pivot_wider(names_from = c("study", "stat")
              , values_from = "value") %>% 
  mutate(term = factor(term, levels = terms$old, labels = terms$new)
         , type = factor(type, c("Fixed", "Random", " "))) %>%
  group_by(Imputed, model, random, int, cov) %>%
  nest() %>%
  ungroup() %>%
  mutate(tab = pmap(list(Imputed, model, random, int, cov, data), stdy_tab_fun))
```

```{r}
formatted_res <- nested_res %>%
  select(Imputed:cov, coef) %>%
  unnest(coef) %>%
  filter(!is.na(term)) %>%
  mutate(pval = pnorm(abs(estimate/`std.error`), lower.tail = FALSE)
         , p = ifelse(pval < .001, "< .001", sprintf("%.2f", pval))
         , type = "Fixed") %>%
  mutate_at(vars(estimate, std.error), ~ifelse(abs(.) < .01, sprintf("%.3f", .), sprintf("%.2f", .))) %>%
  select(Imputed, model, random, int, cov, type, estimate, se = std.error, p, term, study) %>%
  mutate(res = sprintf("(\textit{b} = %s [\textit{SE} = %s], \textit{p} = %s)", estimate, se, p))

formatted_res_wide <- formatted_res %>%
  unite(comb, study, Imputed, model, random, int, cov, term, sep = "_") %>%
  select(comb, res) %>%
  pivot_wider(names_from = "comb", values_from = "res")

formatted_res_wide$ELSA_imp_Linear_slope_Main_adj_functional
```

## Model Comparisons  
```{r}
loadRData <- function(fileName){
#loads an RData file, and returns it
  print(fileName)
    path <- sprintf("%s/03-results/01-models/%s", wd, fileName)
    load(path)
    get(ls()[ls() == "m"])
}

nested_models <- tibble(
  file = sprintf("%s/03-results/01-models", wd) %>% list.files()
) %>%
  separate(file, c("Imputed", "study", "model", "random", "int", "cov"), sep = "_", remove = F) %>% 
  filter(!is.na(cov) & int == "Main" & Imputed == "unimp" & random == "slope" & cov == "none.RData") %>%
  mutate(m = map(file, possibly(loadRData, NA_real_))
         , cov = str_remove_all(cov, ".RData")) %>%
  select(-file) %>%
  filter(study != "BHPS") %>%
  pivot_wider(names_from = "model", values_from = "m")

model_comp_fun <- function(linear, quadratic){
  av <- anova(linear, quadratic)
  av %>% 
    as.data.frame() %>%
    rownames_to_column("model") %>%
    rename(p = `Pr(>Chisq)`)
}

nested_models <- nested_models %>%
  mutate(mod_comp = map2(Linear, Quadratic, model_comp_fun))

model_comp_tab <- nested_models %>%
  select(-Linear, -Quadratic) %>%
  unnest(mod_comp) %>%
  mutate_at(vars(AIC, BIC, logLik, deviance, Chisq), ~sprintf("%.2f", .)) %>%
  mutate_at(vars(npar, Df), ~sprintf("%i", .)) %>%
  mutate(p = sprintf("%.1e", p)
         , model = str_to_title(model)) %>%
  mutate_at(vars(Chisq, Df, p), ~ifelse(. == "NA", "", .)) %>%
  select(-random, -int, -cov, - Imputed) %>%
  kable(.
        , "html"
        , col.names = c("Study", "Model", "# Param", "AIC", "BIC", "LL", "Deviance", "Chi^2", "df", "<em>p</em>")
        , escape = F
        , caption = "<strong>Table SX</strong><br><em>Model Comparison Tests of Linear v Quadratic Loneliness Trends</em>"
          ) %>%
  kable_classic(html_font = "Times New Roman") %>%
  collapse_rows(1:2, valign = "top") %>%
  footnote("Linear models included only intercept and slope (age in years) as fixed and random effects. Quadratic models included intercept, slope, and slope^2 as fixed and random effects.", escape = F); model_comp_tab
save_kable(model_comp_tab, file = sprintf("%s/03-results/10-tables/model_comp.html", wd))
```


f# Meta-Analyses  
## Set Up Data  
```{r}
# need meta analyses of:                                                Imputed   | model     | random    | int       |  cov 
# (1) unadjusted intercept models,                                      unimp     | uncond    | intercept | Main      | unadj
# (2) unadjusted linear models (no random slope, unimputed);            unimp     | linear    | intercept | Main      | unadj
# (3) unadjusted linear models (random slope, unimputed)                unimp     | linear    | slope     | Main      | unadj
# (4) adjusted linear models (random slope, unimputed)                  unimp     | linear    | slope     | Main      | adj
# (5) adjusted linear models (random slope, imputed)                    imp       | linear    | slope     | Main      | adj
# (6) unadjusted interaction linear models (random slope, unimputed)    unimp     | linear    | slope     | Interact  | unadj
# (7) adjusted interaction linear models (random slope, imputed)        imp       | linear    | slope     | Interact  | adj
# (8) unajused quadratic models (no random slope, unimputed)            unimp     | quad      | intercetp | Main      | unadj
# (9) unajused quadratic models (random slope, unimputed)               unimp     | quad      | slope     | Main      | unadj
# (10) adjusted quadratic models (random slope, unimputed)              unimp     | quad      | slope     | Main      | adj
# (11) adjusted quadratic models (random slope, imputed)                imp       | quad      | slope     | Main      | adj
# (12) unadjusted quadratic models (random slope), interactions         unimp     | qad       | slope     | Interact  | adj
# (13) adjusted quadratic models (random slope, imputed), interactions  imp       | qad       | slope     | Interact  | adj

nested_meta <- nested_res %>% 
  unnest(n.group) %>% 
  select(Imputed:cov, coef, n.group) %>%
  unnest(coef) %>%
  select(Imputed:cov, term, estimate, std.error, n.group) %>%
  filter(term != "(Intercept)" & 
         !(grepl("Interaction", int) & !grepl(":", term)) & 
         !(int == "b.age" & !grepl(":", term))) %>% # remove main effects / slopes from interaction models
  group_by(Imputed, model, random, int, cov, term) %>%
  nest() %>%
  ungroup()

## bring in meta regression info
nested_meta <- crossing(
  study.info %>% rename(meta = data), 
  nested_meta %>%
  filter(int == "Main" & term %in% c("age", "age2")) %>%
  select(-int)
) %>%
  mutate(data = map2(data, meta, left_join)) %>%
  select(-meta) %>%
  full_join(nested_meta)
```

## Run Meta-Analyses  
```{r}
meta_fun <- function(imp, mod, rand, int, cov, term, d){
  fm <- if (int %in% c("Main", "Interaction", "AllInteraction", "b.age")) "estimate ~ 1" else "estimate ~ 1 + metamod"
  m <- rma(
    # yi = estimate
    formula(fm)
    , sei = `std.error`
    , ni = n.group
    , slab = study
    , data = d
  )
  
  save(m, file = sprintf("%s/03-results/08-meta-models/%s-%s-%s-%s-%s-%s.RData"
                         , wd, imp, mod, rand, int, cov, term))
  return(m)
}

nested_meta <- nested_meta %>%
  mutate(m = pmap(list(Imputed, model, random, int, cov, term, data)
                  , meta_fun))
```

## Tables  
### Meta-Analytic Effects  
```{r}
stdyModers <- study.info %>% select(-data) %>%
  mutate(new = mapvalues(
    int,
    c("continent", "year", "MO", "interval", "scale", "range"),
    c("Continent", "Year", "# Measurement Occasions", "Interval Between Occasions", "Loneliness Scale", "Interval of Study")
  ))

meta_tab_fun <- function(imp, mod, rand, int, cov, d){
  cap <- if(mod == "unconditional") "Unconditional" else if(int %in% stdyModers$int) sprintf("Loneliness-%s %s meta-regression model", mod, int) else sprintf("Loneliness-%s model", mod)
  cap <- paste(cap, if(int == "Interaction") "with Predictor Main Effects and Interactions" else if(int == "b.age") "with Predictor Main Effects and Baseline Age Interactions" else "with Predictor Main Effects") 
  cap <- paste(if(cov == "adj") "Covariate Adjusted" else "Unadjusted", cap)
  if(int %in% stdyModers$int) {
    cn <- c("Term", "Meta-Moderator", "B", "SE", "p")
    al <- c("r", "r", rep("c", 3))
  } else{
    cn <- c("Term", "B", "SE", "p")
    al <- c("r", rep("c", 3))
    d <- d %>% select(-metaterm)
  }
  tab <- d %>%
    mutate(term = mapvalues(term, terms$old, terms$new, warn_missing = F)) %>%
    kable(.
          , "html"
          , escape = F
          , align = al
          , col.names = cn
          , caption = cap
          , booktabs = T
          ) %>%
    kable_classic(full_width = F, font_size = 12, html_font = "Times New Roman")
  save_kable(tab, file = sprintf("%s/03-results/10-tables/meta-tables/%s_%s_%s_%s_%s.html"
                                 , wd, imp, mod, rand, int, cov))
  return(tab)
}

nested_meta_tab <- nested_meta %>%
  mutate(tidy = map(m, ~tidy(.) %>% 
                      select(-type) %>%
                      rename(metaterm = term) %>%
                      mutate(study = "meta"))
         ) %>%
  select(-data, -m) %>%
  unnest(tidy) %>% 
  mutate(metaterm = ifelse(metaterm == "metamod", int, metaterm)) %>%
  filter(!(int %in% stdyModers$int & metaterm == "intercept")) %>%
  mutate(sig = ifelse(p.value < .05, "sig", "ns")
         , p = ifelse(p.value < .001, "&lt; .001", sprintf("%.2f", p.value))) %>%
  mutate_at(vars(estimate, std.error), ~ifelse(abs(.) < .01, sprintf("%.3f", .), 
                               sprintf("%.2f", .))) %>%
  mutate_at(vars(estimate, std.error, p), ~ifelse(sig == "sig", sprintf("<strong>%s</strong>", .), .)) %>%
  select(Imputed, model, random, int, cov, term, metaterm, estimate, std.error, p) 

nested_metamod_tab <- nested_meta_tab %>%
  filter(int %in% stdyModers$int)

nested_meta_tab <- nested_meta_tab %>%
  filter(!int %in% stdyModers$int) %>%
  group_by(Imputed, model, random, int, cov) %>%
  nest() %>%
  ungroup() %>%
  mutate(tab = pmap(list(Imputed, model, random, int, cov, data), meta_tab_fun))
```

```{r}
metamod_tab_fun <- function(imp, mod, rand, cov, d){
  cap <-  sprintf("Loneliness-%s Meta-Regression Models", mod) 
  cap <- paste(cap, "with Predictor Main Effects") 
  cap <- paste(if(cov == "adj") "Covariate Adjusted" else "Unadjusted", cap)
  cn <- c("Meta-Moderator", "Term", "Meta-Term", "B", "SE", "p")
  al <- c(rep("r", 3), rep("c", 3))
  tab <- d %>%
    mutate(term = mapvalues(term, terms$old, terms$new, warn_missing = F)
           , metaterm = mapvalues(metaterm, terms$old, terms$new, warn_missing = F)
           , int = mapvalues(int, stdyModers$int, stdyModers$new, warn_missing = F)) %>%
    kable(.
          , "html"
          , escape = F
          , align = al
          , col.names = cn
          , caption = cap
          , booktabs = T
          ) %>%
    kable_classic(full_width = F, font_size = 12, html_font = "Times New Roman")
  save_kable(tab, file = sprintf("%s/03-results/10-tables/meta-tables/%s_%s_%s_metamod_%s.html"
                                 , wd, imp, mod, rand, cov))
  return(tab)
}

nested_metamod_tab <- nested_metamod_tab %>%
  filter(!(model == "Quadratic" & term == "age")) %>%
  group_by(Imputed, model, random, cov) %>%
  nest() %>%
  ungroup() %>%
  mutate(tab = pmap(list(Imputed, model, random, cov, data), metamod_tab_fun))
```


```{r}
meta_res <- nested_meta %>%
    mutate(tidy = map(m, ~tidy(.) %>% 
                      select(-type) %>%
                      rename(metaterm = term) %>%
                      mutate(study = "meta"))
           ) %>%
    select(-data, -m) %>%
    unnest(tidy) %>% mutate(metaterm = ifelse(metaterm == "metamod", int, metaterm)) %>%
  # filter(!(int %in% stdyModers$int & metaterm == "intercept")) %>%
    mutate(sig = ifelse(p.value < .05, "sig", "ns")
           , p = ifelse(p.value < .001, "&lt; .001", sprintf("%.2f", p.value))
           , estimate = ifelse(abs(estimate) < .01, sprintf("%.3f", estimate), 
                               sprintf("%.2f", estimate))
           , std.error = ifelse(abs(std.error) < .01, sprintf("%.3f", std.error), 
                               sprintf("%.2f", std.error))
           , res = sprintf("(*B* = %s [*SE* = %s], *p* = %s)", estimate, std.error, p)) %>%
  select(int:term, metaterm, res)

metamod_res <- meta_res %>%
  filter(int %in% stdyModers$int) %>%
  pivot_wider(names_from = c("Imputed", "model", "random", "int", "cov", "term", "metaterm")
              , values_from = "res")

meta_res <- meta_res %>% 
  filter(!int %in% stdyModers$int) %>%
  select(-metaterm) %>%
  pivot_wider(names_from = c("Imputed", "model", "random", "int", "cov", "term")
              , values_from = "res")

save(meta_res, file = sprintf("%s/03-results/meta_res.RData", wd))

meta_res$imp_Linear_slope_Main_adj_functional
```


### Study Specific + Meta-Analytic Effects  
```{r}
meta_std_tab_fun <- function(imp, mod, rand, int, cov, d){
  trms <- unique(d$term)
  cols <- paste(rep(c("estimate", "std.error", "p"), times = length(trms)), rep(trms, each = 3), sep = "_")
  new <- mapvalues(trms, terms$old, terms$new, warn_missing = F)
  hdr <- c(1, rep(3, length(trms))); names(hdr) <- c(" ", new)
  cap <- if(mod == "unconditional") "Unconditional" else sprintf("Loneliness-%s model", mod)
  cap <- paste(cap, if(grepl("Interaction", int)) "with Predictor Main Effects and Interactions" else if(int == "b.age") "with Predictor Main Effects and Baseline Age Interactions" else "with Predictor Main Effects") 
  cap <- paste(if(cov == "adj") "Covariate Adjusted" else "Unadjusted", cap)
  tab <- d %>% 
    mutate(sig = ifelse(p.value < .05, "sig", "ns")
           , p = ifelse(p.value < .001, "&lt; .001", sprintf("%.2f", p.value))
           , estimate = ifelse(abs(estimate) < .01, sprintf("%.3f", estimate), sprintf("%.2f", estimate))
           , std.error = ifelse(abs(std.error) < .01, sprintf("%.3f", std.error), sprintf("%.2f", std.error))) %>%
    mutate_at(vars(estimate, std.error, p), ~ifelse(sig == "sig", sprintf("<strong>%s</strong>", .), .)) %>%
    select(-statistic, -p.value, -sig) %>%
    pivot_wider(names_from = "term", values_from = c("estimate", "std.error", "p")) %>%
    select(study, one_of(cols)) %>%
    kable(.
          , "html"
          , col.names = c("Study", rep(c("<em>B</em>", "<em>SE</em>", "<em>p</em>"), times = length(trms)))
          , escape = F
          , align = c("r", rep("c", length(trms)*3))
          , caption = cap
          , booktabs = T
          ) %>%
    kable_classic(full_width = F, font_size = 12, html_font = "Times New Roman") %>%
    add_header_above(hdr)
  save_kable(tab, file = sprintf("%s/03-results/10-tables/meta-study-tables/%s_%s_%s_%s_%s.html"
                                 , wd, imp, mod, rand, int, cov))
  return(tab)
}

nested_meta_std_tabs <- nested_res %>% 
  select(Imputed:cov, coef) %>%
  unnest(coef) %>%
  filter(!is.na(term)) %>%
  mutate(p.value = pnorm(abs(estimate/`std.error`), lower.tail = FALSE)) %>%
  select(Imputed:cov, term, estimate, std.error, statistic, p.value) %>%
  filter(term != "(Intercept)" & 
         !(grepl("Interaction", int) & !grepl(":", term))) %>%
  full_join(
    nested_meta %>%
      mutate(tidy = map(m, ~tidy(.) %>% 
                          select(-type, -term) %>%
                          mutate(study = "Meta-Analytic"))
             ) %>%
      select(-data, -m) %>%
      unnest(tidy)
  ) %>%
  group_by(Imputed, model, random, int, cov) %>%
  nest() %>%
  ungroup() %>%
  mutate(tab = pmap(list(Imputed, model, random, int, cov, data), meta_std_tab_fun))

meta_std_tabs <- nested_meta_std_tabs %>% 
  select(-data) %>%
  pivot_wider(names_from = c("Imputed", "model", "random", "int", "cov"), 
              values_from = "tab",
              names_sep = "_")

meta_std_tabs$imp_Linear_slope_Interaction_adj[[1]]
```

## Plots  
### Compile Plot Data  
```{r}
loadRData <- function(fileName){
#loads an RData file, and returns it
  print(fileName)
    path <- sprintf("%s/03-results/02-predicted/%s", wd, fileName)
    load(path)
    if(!any(is.na(m))){
      cols <- c("drink", "smoke", "cc")
      cols <- cols[cols %in% colnames(m)]
      m <- m %>% mutate_at(vars(one_of(cols)), ~as.numeric(as.character(.)))
    }
    get(ls()[ls() == "m"])
}

nested_plots <- tibble(
  file = sprintf("%s/03-results/02-predicted", wd) %>% list.files()
) %>%
  separate(file, c("Imputed", "study", "model", "random", "int", "cov"), sep = "_", remove = F) %>%
  mutate(data = map(file, loadRData)
         , cov = str_remove_all(cov, ".RData")) %>%
  select(-file) %>%
  filter(!is.na(data)) %>%
  filter(study != "BHPS") %>%
  filter(!(study == "OCTOTWIN" & model == "Quadratic" & grepl("Interaction", int))) %>%
  unnest(data) 
```

### Main Effects  
```{r}
traj_plot_fun <- function(mod, cov, imp, random, d){
  cap <- if(mod == "unconditional") "Unconditional" else sprintf("Loneliness-%s model", mod)
  cap <- paste(cap, "with Predictor Main Effects") 
  cap <- paste(if(cov == "adj") "Covariate Adjusted" else "Unadjusted", cap)
  frm <- if(mod == "Quadratic") "y ~ x + I(x^2)" else "y ~ x"
  d <- d %>% mutate(study = factor(study, levels = stdcolors$studies))
  std <- unique(d$study)
  cols <- (stdcolors %>% filter(studies %in% std))$colors
  p <- d %>%
    group_by(study, age, n.group) %>%
    summarize(fit = mean(fit)) %>%
    ggplot(aes(x = age*10 + 60, y = fit)) + 
    geom_line(aes(color = study), size = 1) + 
    stat_smooth(aes(weight = n.group),
              method = "lm",
              formula = frm,
              size = 1.2, color = "black") +
    scale_color_manual(values = cols)+
    scale_y_continuous(limits = c(0, 5.5), breaks = seq(1,5,1)) + 
    coord_cartesian(
      xlim = c(20, 105)
      ) + 
    labs(x = "Age in Years"
         , y = "Loneliness"
         , color = "Sample"
         # , title = cap
         )  +
    guides(color = guide_legend(override.aes = list(size = 0.5), nrow = 3)) +
    theme_classic() +
    theme(
      legend.position = "bottom"
      , plot.title = element_text(face = "bold", hjust = .5)
      , axis.text = element_text(face = "bold", color = "black", size = rel(1))
      , axis.title = element_text(face = "bold", size = rel(1.1))
      , legend.text = element_text(size = rel(1))
      , legend.title = element_text(face = "bold", size = rel(1.1))
      , strip.text = element_text(face = "bold", color = "white", size = rel(1.1))
      , strip.background = element_rect(fill = "grey40", color = "black")
      )
  ggsave(p, file = sprintf("%s/03-results/09-plots/01-trajectories/main/%s-%s-%s-%s.png", wd, imp, mod, random, cov)
         , width = 8, height = 6)
  ggsave(p, file = sprintf("%s/03-results/09-plots/01-trajectories/main/pdf/%s-%s-%s-%s.pdf", wd, imp, mod, random, cov)
         , width = 8, height = 6)
  return(p)
}

me_traj_plots <- nested_plots %>% 
  filter(int == "Main") %>%
  left_join(nested_res %>% select(Imputed:cov, n.group) %>% unnest(n.group)) %>%
  group_by(Imputed, model, random, cov) %>%
  nest() %>%
  ungroup() %>%
  mutate(p = pmap(list(model, cov, Imputed, random, data), traj_plot_fun))
```

### Interaction Plots  
```{r}
mod_vals <- tribble(
  ~old            , ~new                         , ~group
  , "maritalA"    , "Married"                    , "marital"
  , "maritalB"    , "Divorced"                   , "marital"
  , "maritalC"    , "Widowed"                    , "marital"
  , "maritalD"    , "Never Married"              , "marital"
  , "sex0"        , "Male"                       , "sex"
  , "sex1"        , "Female"                     , "sex"
  , "functional-1", "Low Functional Limitations" , "functional"
  , "functional1" , "High Functional Limitations", "functional"
  , "educ-1"      , "Low Education"              , "educ"
  , "educ1"       , "High Social Education"      , "educ"
  , "b.isolated-1", "Low Social Isolation"       , "b.isolated"
  , "b.isolated1" , "High Social Isolation"      , "b.isolated"
  , "b.age-4"    , "Low Baseline Age"           , "b.age"
  , "b.age0"     , "High Baseline Age"          , "b.age"
  , "bmi-1"       , "Low BMI"                    , "bmi"
  , "bmi1"        , "High BMI"                   , "bmi"
  , "income-1"    , "Low Baseline Income"        , "income"
  , "income1"     , "High Baseline Income"       , "income"
  , "drink0"      , "Non-Drinker"                , "drink"
  , "drink1"      , "Drinks Alcohol"             , "drink"
  , "smoke0"      , "Non-Smoker"                 , "smoke"
  , "smoke1"      , "Smokes"                     , "smoke"
  , "episodic-1"  , "Low Episodic Memory"        , "episodic"
  , "episodic1"   , "High Episodic Memory"       , "episodic"
  , "mstat-1"     , "Low MMSE"                   , "mstat"
  , "mstat1"      , "High MMSE"                  , "mstat"
  , "depression0"  , "Low Depressive Symptoms"    , "depression"
  , "depression1"  , "High Deprssive Symptoms"    , "depression"
  , "cc0"         , "Low Chronic Coniditions"    , "cc"
  , "cc1"         , "High Chronic Coniditions"   , "cc"
)

int_plot_fun <- function(d, int, mod, cov, random, imp){
  print(paste(int, mod, cov, random, imp))
  frm <- if(mod == "Quadratic") "y ~ x + I(x^2)" else "y ~ x"
  mv <- mod_vals %>%
    filter(group == int)
  ht <- if(int == "marital") 10 else 6
  d <- d %>% mutate(study = factor(study, levels = stdcolors$studies))
  std <- unique(d$study)
  cols <- (stdcolors %>% filter(studies %in% std))$colors
  if(int == "b.age"){
    d <- d %>%
      filter((b.age == 0 & age > 0) | (b.age == -4 & age < 1))
  }
  p <- d %>% 
    select(study, age, fit, int, n.group) %>%
    setNames(c("study", "age", "fit", "mod_value", "n")) %>%
    mutate(mod_value = paste(int, mod_value, sep = "")
           , mod_value = factor(mod_value, mv$old, mv$new)) %>%
    group_by(study, age, mod_value, n) %>%
    summarize(fit = mean(fit, na.rm = T)) %>%
    ungroup() %>%
    filter(!is.na(mod_value) & fit >= 0 & fit <= 10) %>%
    ggplot(aes(x = age*10 + 60, y = fit)) +
      geom_line(aes(color = study
                    , group = interaction(study, factor(mod_value)))
                , size = 1) + 
      stat_smooth(aes(weight = n
                      , group = factor(mod_value))
                  , method = "lm"
                  , formula = frm
                  , size = 1.2
                  , color = "black"
                  ) +
    scale_color_manual(values = cols) + 
    labs(x = "Age in Years"
         , y = "Loneliness"
         , color = "Sample"
         # , title = cap
         )  +
    facet_wrap(~mod_value) + 
    theme_classic() + 
    theme(
      legend.position = "bottom"
      , plot.title = element_text(face = "bold", hjust = .5)
      , axis.text = element_text(face = "bold", color = "black", size = rel(1))
      , axis.title = element_text(face = "bold", size = rel(1.1))
      , legend.text = element_text(size = rel(1))
      , legend.title = element_text(face = "bold", size = rel(1.1))
      , strip.text = element_text(face = "bold", color = "white", size = rel(1.1))
      , strip.background = element_rect(fill = "grey40", color = "black")
      )
  ggsave(p, file = sprintf("%s/03-results/09-plots/01-trajectories/%s/%s-%s-%s-%s.png", wd, int, imp, mod, random, cov)
         , width = 8, height = ht)
  ggsave(p, file = sprintf("%s/03-results/09-plots/01-trajectories/%s/pdf/%s-%s-%s-%s.pdf", wd, int, imp, mod, random, cov)
         , width = 8, height = ht)
  return(p)
}

orig_int <- c("b.isolated", "sex", "marital", "b.age", "functional", "educ")
new_int  <- c("income", "drink", "smoke", "bmi", "cc", "depression", "episodic", "mstat")
int_traj_plots <- nested_plots %>% 
  filter(int != "Main") %>% #& int != "b.age") %>%
  left_join(nested_res %>% select(Imputed:cov, n.group) %>% unnest(n.group)) %>%
  group_by(int, Imputed, model, random, cov) %>%
  nest() %>% 
  ungroup()

int_traj_plots <- crossing(
  int_traj_plots
  , term = c("b.isolated", "marital", "sex", "functional", "educ", "b.age"
   , "income", "drink", "smoke", "bmi", "cc", "depression", "episodic", "mstat")
  ) %>%
  filter(!grepl("Interaction", int) | 
         (int == "Interaction" & term %in% orig_int) |
         (int == "AllInteraction" & !term %in% orig_int)) %>%
  filter(!(int == "b.age" & term != "b.age")) %>%
  mutate(p = pmap(list(data, term, model, cov, random, Imputed), possibly(int_plot_fun, NA_real_)))
```

### Forest Plots  

```{r}
f_plot_fun <- function(d, trm, imp, mod, random, int, cov, I2, Q, p, df){
  # print(trm, imp, mod, random, int, cov)
  trm2 <- mapvalues(trm, terms$old, terms$new, warn_missing = F)
  cap <- if(mod == "unconditional") "Unconditional" else sprintf("Loneliness-%s model", mod)
  cap <- paste(cap, if(int == "Interaction") "with Predictor Main Effects and Interactions" else if(int == "b.age") "with Predictor Main Effects and Baseline Age Interactions" else "with Predictor Main Effects") 
  cap <- paste(if(cov == "adj") "Covariate Adjusted" else "Unadjusted", cap)
  cap <- paste(trm2, cap, sep = ": ")
  ef <- round(max(abs(min(d$estimate)), abs(max(d$estimate))), 2) 
  lim <- c(0-ef-(ef/2.5), ef+(ef/2.5))
  brk <- round(c(0-ef-(ef/5), 0, ef+(ef/5)),2)
  lab <- str_remove(round(c(0-ef-(ef/5), 0, ef+(ef/5)),2), "^0")
  d <- d %>% full_join(tibble(study = " ", estimate = NA, n.group = NA))
  d <- d %>% arrange(estimate)
  stds <- d$study[!d$study %in% c("Meta-Analytic", " ")]
  d <- d %>%
    mutate(study = factor(study, rev(c(" ", stds, "Meta-Analytic")))
           , lb = ifelse(lower < lim[1], "lower"
                         , ifelse(upper > lim[2], "upper", "neither"))
           , lower2 = ifelse(lower < lim[1], lim[1], lower)
           , upper2 = ifelse(upper > lim[2], lim[2], upper))
  p1 <- d %>%
    mutate(meta = ifelse(study == "Meta-Analytic", "Meta-Analytic", "study")) %>%
    ggplot(aes(x = study, y = estimate)) + 
      geom_errorbar(aes(ymin = lower, ymax = upper)
                    , position = "dodge"
                    , width = .2) + 
      geom_point(aes(shape = meta, size = meta)) + 
      geom_segment(data = d %>% filter(lb == "lower")
                 , aes(y = upper2, yend = lower2, xend = study)
                 , arrow = arrow(type = "closed", length = unit(0.1, "cm"))) +
      geom_segment(data = d %>% filter(lb == "upper")
                 , aes(y = lower2, yend = upper2, xend = study)
                 , arrow = arrow(type = "closed", length = unit(0.1, "cm"))) +
      geom_hline(aes(yintercept = 0), linetype = "dashed", size = .5) +
      geom_vline(aes(xintercept = 1.5)) +
      geom_vline(aes(xintercept = length(stds) + 1.5)) +
      annotate("rect", xmin = length(stds) + 1.6, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "white") +
      scale_y_continuous(limits = lim, breaks = brk, labels = lab) + 
      scale_size_manual(values = c(4,2)) + 
      scale_shape_manual(values = c(15, 16)) +
      labs(x = NULL
           , y = "Estimate"
           # , title = "  "
           ) +
      coord_flip() + 
      theme_classic() + 
      theme(legend.position = "none"
            , axis.text = element_text(face = "bold")
            , axis.title = element_text(face = "bold")
            , plot.title = element_text(face = "bold", hjust = .5)
            , axis.ticks.y = element_blank()
            , axis.line.y = element_blank()
            , axis.line.x.top = element_line(size = 1))
  d2 <- d %>%
    mutate_at(vars(estimate, lower, upper)
              , ~ifelse(abs(.) < .01, sprintf("%.3f", .), sprintf("%.2f", .))) %>%
    mutate(est = ifelse(study != " ", sprintf("%s [%s, %s]      ", estimate, lower, upper), ""),
           n.group = as.character(n.group)) %>%
    select(study, n.group, est) %>%
    pivot_longer(cols = c(n.group, est), names_to = "est", values_to = "value")
  p2 <- d2 %>%
    ggplot(aes(x = study, y = est)) +
      geom_text(aes(label = value), hjust = .5, size = 3.5) + 
      annotate("text", label = "b [CI]", x = length(stds) + 1.75, y = "est", hjust = .5, vjust = 0, fontface = "bold") +
      annotate("text", label = "N", x = length(stds) + 1.75, y = "n.group", hjust = .5, vjust = 0, fontface = "bold") +
      geom_vline(aes(xintercept = 1.5)) +
      geom_vline(aes(xintercept = length(stds) + 1.5)) +
      coord_flip() +
      theme_void() +
      theme(plot.title = element_text(face = "bold", hjust = 0)
            , axis.text = element_blank()
            , axis.ticks = element_blank()
            , axis.title = element_blank())
  
  # setup title text
  my_theme <- function(...) {
    theme_classic() + 
      theme(plot.title = element_text(face = "bold", hjust = .5)
            , plot.subtitle = element_text(face = "italic", hjust = .5))
  }
  if(grepl("Age\\^2", trm2)) {
    trm2 <- str_remove_all(trm2, "Age\\^2")
    trm2 <- substitute(paste(Age^2, trm2))
  }
  title_theme <- calc_element("plot.title", my_theme())
  ttl <- ggdraw() +
      draw_label(
          trm2,
          fontfamily = title_theme$family,
          fontface = title_theme$face,
          size = title_theme$size
      )
  
  # setup subtitle text
  subtitle_theme <- calc_element("subplot.title", my_theme())
  subttl <- ggdraw() +
      draw_label(
          substitute(
               paste("RE Model (Q = ", Q1, ", df = ", df1, ", p = ", p1, ", ", I^2, " = ", I21, ")")
               , list(Q1 = round(Q,2), df1 = df, p1 = round(p,3), I21 = round(I2,2))),
          fontfamily = subtitle_theme$family,
          fontface = subtitle_theme$face,
          size = subtitle_theme$size
      )
  
  # piece the plots together
  p3 <- p1 + p2 + plot_layout(widths = c(4,6))
  
  # add the title and subtitle
  p <- cowplot::plot_grid(ttl, subttl, p3, rel_heights = c(.1, .05, .85), nrow = 3)
  trm <- str_replace_all(trm, ":", "X")
  ggsave(p, file = sprintf("%s/03-results/09-plots/02-forest-plots/%s-%s-%s-%s-%s-%s.pdf", 
                           wd, trm, imp, mod, random, int, cov)
         , width = 6, height = 3)
  ggsave(p, file = sprintf("%s/03-results/09-plots/02-forest-plots/png/%s-%s-%s-%s-%s-%s.png", 
                           wd, trm, imp, mod, random, int, cov)
         , width = 6, height = 3)
  return(p)
}

fplot_nested <- nested_res %>% 
  select(Imputed:cov, n.group, coef) %>%
  unnest(n.group) %>%
  unnest(coef) %>%
  select(Imputed:cov, term, estimate, std.error, statistic, p.value, n.group) %>%
  filter(term != "(Intercept)" & 
         !(int %in% c("Interaction", "AllInteraction") & !grepl(":", term)) & 
         !(int == "b.age" & !grepl(":", term))) %>%
  full_join(
    nested_meta %>%
      mutate(tidy = map(m, ~tidy(.) %>% 
                          select(-type, -term) %>%
                          mutate(study = "Meta-Analytic"))
             ) %>%
      select(-data, -m) %>%
      filter(term != "(Intercept)" & 
         !(int %in% c("Interaction", "AllInteraction") & !grepl(":", term)) & 
         !(int == "b.age" & !grepl(":", term))) %>%
      unnest(tidy)
  ) %>%
  mutate(lower = estimate - 1.96*std.error
         , upper = estimate + 1.96*std.error) %>%
  group_by(Imputed, model, random, int, cov, term) %>%
  mutate(n.group = ifelse(study == "Meta-Analytic", sum(n.group, na.rm = T), n.group)) %>%
  nest() %>%
  ungroup() %>%
  full_join(
    nested_meta %>%
      mutate(I2 = map_dbl(m, ~(.)$I2)
             , Q = map_dbl(m, ~(.)$QE)
             , p = map_dbl(m, ~(.)$QEp)
             , df = map_dbl(m, ~(.)$k - (.)$p)
             ) %>%
      select(-data, -m)) %>%
  filter(!map_lgl(data, is.null)) %>%
  mutate(p = pmap(list(data, term, Imputed, model, random, int, cov, I2, Q, p, df), f_plot_fun))
```

#### Panels by Model  
```{r}
fp_group_plot_fun <- function(d, imp, mod, rand, int, cov){
  
  ttl <- if(grepl("Interaction", int)) sprintf("%s Change in Loneliness", mod) else "Loneliness Levels"
  ttl <- sprintf("Forest Plots of Predictors of %s", ttl)
  
  my_theme <- function(...) theme_classic() + theme(plot.title = element_text(face = "bold", hjust = .5))
  
  p <- (d$p[[1]] + d$p[[2]]) / 
    (d$p[[3]] + d$p[[6]]) /
    (d$p[[4]] + d$p[[7]]) / 
    (d$p[[5]] + d$p[[8]]) + 
    plot_annotation(
      title = ttl
      , theme = my_theme()
    )
  
  ggsave(p, file = sprintf("%s/03-results/09-plots/03-forest-plot-panels/%s-%s-%s-%s-%s.png"
                        , wd, imp, mod, rand, int, cov)
         , width = 11.5
         , height = 14)
  ggsave(p, file = sprintf("%s/03-results/09-plots/03-forest-plot-panels/%s-%s-%s-%s-%s.pdf"
                        , wd, imp, mod, rand, int, cov)
         , width = 11.5
         , height = 14)
  return(p)
}

fplot_nested_gr <- fplot_nested %>% 
  filter((Imputed == "imp" & model == "Linear" & random == "slope" & int == "Main" & 
        term %in% c("b.isolated", "sex", "maritalB", "maritalC", "maritalD", "b.age", "functional", "educ")) | 
         (Imputed == "imp" & model == "Linear" & random == "slope" & int == "Interaction")| 
         (Imputed == "imp" & model == "Quadratic" & random == "slope" & int == "Interaction" & grepl("age2", term)) |  
        
         (Imputed == "imp" & model == "Linear" & random == "slope" & int == "AllInteraction" & term %in% paste0("age:", new_int)) | 
         (Imputed == "imp" & model == "Quadratic" & random == "slope" & int == "AllInteraction" & grepl("age2", term) & term %in% paste0(new_int, ":age2"))) %>%
  full_join(fplot_nested %>% 
              filter((Imputed == "imp" & model == "Linear" & random == "slope" & int == "Main" & 
        term %in% new_int)) %>% 
          mutate(int = "AllMain")) %>%
  select(-data) %>%
  group_by(Imputed, model, random, int, cov) %>%
  nest() %>%
  ungroup() %>%
  mutate(p = pmap(list(data, Imputed, model, random, int, cov), fp_group_plot_fun))
```

#### Forest Plot + Simple Slopes Panels  

```{r}
fplot_int_panel_fun <- function(fp, p, imp, mod, rand, int, cov, term){
  # setup term names for title
  trm <- if(int == "Interaction"){
    if(mod == "Linear") "Age" else "Age\\^2"
  } else {
    "Baseline Age"
  }
  # change to prettified names
  term2 <- mapvalues(term, terms$old, terms$new, warn_missing = F)
  # create the title
  ttl <- sprintf("Forest Plots and Simple Effects of the %s x %s Interaction", trm, term2)
  # format special characters
  if(grepl("Age\\^2", ttl)) {
    ttl <- str_remove_all(ttl, "Age\\^2")
    ttl <- substitute(paste(Age^2, ttl))
  }
  # setup title and themes
  my_theme <- function(...) {
    theme_classic() + 
      theme(plot.title = element_text(face = "bold"))
  }
  title_theme <- calc_element("plot.title", my_theme())
  ttl <- ggdraw() + 
      draw_label(
          ttl,
          fontfamily = title_theme$family,
          fontface = title_theme$face,
          size = title_theme$size
      )
  # generate plots differently for multilevel factors (marital)
  # v. continuous or binary factors
  if(term == "marital"){
    p1 <- (fp$p[[1]] / fp$p[[2]] / fp$p[[3]]) 
    p2 <- plot_grid(p1, p, nrow = 1)
    wdt <- 12; ht <- 10
  } else {
    p2 <- fp$p[[1]] + p
    wdt <- 12; ht <- 6
  }
  # piece together and save
  p <- cowplot::plot_grid(ttl, p2, rel_heights = c(.1, .9), nrow = 2)
  ggsave(p
         , file = sprintf("%s/03-results/09-plots/05-forest-plot-int-panels/%s-%s-%s-%s-%s-%s.png", wd, imp, mod, rand, int, cov, term)
         , width = wdt
         , height = ht)
  ggsave(p
         , file = sprintf("%s/03-results/09-plots/05-forest-plot-int-panels/%s-%s-%s-%s-%s-%s.pdf", wd, imp, mod, rand, int, cov, term)
         , width = wdt
         , height = ht)
}

fplot_int_panels <- fplot_nested %>%
  separate(term, c("scrap", "term"), sep = ":") %>%
  mutate(term = ifelse(is.na(term), scrap, term)) %>%
  select(Imputed:cov, term, p) %>%
  mutate(group = mapvalues(term, mod_vals$old, mod_vals$group, warn_missing = F)) %>%
  group_by(Imputed, model, random, int, cov, group) %>%
  nest() %>%
  ungroup() %>%
  rename(term = group) %>%
  right_join(int_traj_plots %>% select(-data)) %>%
  mutate(pp = pmap(list(data, p, Imputed, model, random, int, cov, term), fplot_int_panel_fun))
```

```{r}
fplot_me_panel_fun <- function(fp, p, imp, mod, rand, int, cov, term){
  # setup term names for title
  # change to prettified names
  # term2 <- mapvalues(term, terms$old, terms$new, warn_missing = F)
  # create the title
  ttl <- sprintf("%s Change in Loneliness Across the Lifespan", mod)
  subttl <- "Forest Plot and Trajectories"
  my_theme <- function(...) {
    theme_classic() + 
      theme(plot.title = element_text(face = "bold", hjust = .5)
            , plot.subtitle = element_text(face = "italic", hjust = .5))
  }
  # v. continuous or binary factors
  p <- fp + p + 
    plot_layout(widths = c(5.5,4.5)) + 
    plot_annotation(
      title = ttl
      , subtitle = subttl
      , theme = my_theme()
      , tag_levels = "A"
    )
  # piece together and save
  # p <- cowplot::plot_grid(ttl, p2, rel_heights = c(.1, .9), nrow = 2)
  ggsave(p
         , file = sprintf("%s/03-results/09-plots/05-forest-plot-int-panels/%s-%s-%s-%s-%s-%s.png", wd, imp, mod, rand, int, cov, term)
         , width = 11
         , height = 6)
  ggsave(p
         , file = sprintf("%s/03-results/09-plots/05-forest-plot-int-panels/%s-%s-%s-%s-%s-%s.pdf", wd, imp, mod, rand, int, cov, term)
         , width = 11
         , height = 6)
}

fplot_nested %>% 
  filter(
    int == "Main" 
    & term %in% c("age", "age2") 
    & !(model == "Quadratic" & term == "age")
    ) %>%
  select(Imputed:term, fp = p) %>%
  left_join(
    me_traj_plots %>% select(-data) 
  ) %>%
  mutate(pp = pmap(list(fp, p, Imputed, model, random, int, cov, term), fplot_me_panel_fun))
```



### Baseline Age Simple Slopes  

```{r}
loadRData <- function(fileName){
#loads an RData file, and returns it
  print(fileName)
  path <- sprintf("%s/03-results/11-b.age-int-slopes/%s", wd, fileName)
  load(path)
  get(ls()[ls() == "se"])
}

nested_se <- tibble(file = sprintf("%s/03-results/11-b.age-int-slopes", wd) %>% list.files()) %>%
  separate(file, c("Imputed", "study", "model", "random", "int", "cov"), sep = "_", remove = F) %>%
  mutate(se_res = map(file, loadRData)
         , cov = str_remove_all(cov, ".RData"))
```

```{r}
function(d, mod, term){
  d %>%
    mutate(age = ifelse(grepl("age20", term), "Age 20", ifelse(grepl("age40", term), "Age 40", "Age 60"))
           , age = fct_rev(factor(age))) %>%
    ggplot(aes(x = Estimate, y = age)) + 
      geom_vline(aes(xintercept = 0), linetype = "dashed") + 
      geom_errorbar(
        aes(xmin = lwr, xmax = upr)
        , position = position_dodge(.9)
        , width = .2) + 
      geom_point(
        aes(fill = age)
        , shape = 22
        , color = "black"
        , position = position_dodge(.9)
        , size = 2
        ) + 
      labs(
        x = "Estimated Association [95% CI]"
        , y = NULL
        , title = sprintf("Baseline Age x %s", term)
        , subtitle = "Simple Effects Across Age Groups"
        ) + 
      facet_grid(study ~ . ) + 
      theme_classic() + 
      theme(
        legend.position = "none"
        , panel.border = element_rect(fill = NA, color = "grey80", size = 1)
        , axis.text = element_text(color = "black", size = rel(.9), face = "bold")
        , axis.title = element_text(face = "bold", size = rel(1.1))
        , plot.title = element_text(face = "bold", size = rel(1.2), hjust = .5)
        , plot.title = element_text(face = "italics", size = rel(1), hjust = .5)
        , strip.placement = "outside"
        , strip.text.y = element_text(face = "bold", angle = 0)
        , 
      )
}

nested_se %>%
  filter(study != "OCTOTWIN") %>%
  unnest(se_res) %>%
  mutate(me_term = str_remove_all(term, "age20-")
         , me_term = str_remove_all(me_term, "age40-")
         , me_term = str_remove_all(me_term, "age60-")) %>%
  group_by(model, Imputed, me_term) %>% 
  nest()
```



