---
title: "04-meas-invar"
output: html_document
date: "2022-12-22"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 1: Combine Data  
```{r meas inv load combined data}
loadRData <- function(fileName, type){
#loads an RData file, and returns it
  print(fileName)
    path <- sprintf("%s/01-data/clean/%s_mi.RData", wd, fileName)
    load(path)
    get(ls()[grepl(type, ls())])
}

nested_data <- tibble(
  study = c("LISS", "SHP", "GSOEP", "SATSA", "HILDA", "OCTOTWIN", "SHARE", "HRS", "ELSA")
  # study = c("SHP")
  , data = map(str_to_lower(study), ~loadRData(., "mi$"))
  ); nested_data

missing_fun <- function(d, study){
  sprintf("NOTE: A total of %s cases in %s have loneliness data and will be included in the final analyses.\n"
          , nrow(d), study)
}
print(map2(nested_data$data, nested_data$study, missing_fun))
```

## Measurement Invariance  

```{r meas inv functions}
mi_fun <- function(df){
  # df2 <- df[,-1]; df3 <- df2[,apply(df2, 2, function(x) !is.na(sd(x, na.rm = T)))]
  df2 <- df %>% select(-SID)
  df2 <- df2[,apply(df2, 2, function(x) sum(!is.na(x))/length(x) > .1)]
  df2$SID <- df$SID
  comps <- str_split(names(df2)[!names(df2) == "SID"], pattern = "_") %>% ldply
  lind <- unique(comps$V1); lfac <- list(lonely = paste0("T", unique(comps$V2)))
  f <- map_chr(unique(comps$V2), 
               ~paste(
                 paste0("T", .) # latent variable
                 , paste(
                   unique(comps$V1), ., sep = "_", collapse = " + "
                   ) # items
                 , sep = " =~ ")
               ) %>%  # combine latent and indicators
    paste(., collapse = "\n")
    args <- list(f
                 , data = df2
                 # , ordered = unlist(lfac)
                 , missing = "FIML"
                 , optim.force.converged = T
                 , return.fit = T
                 , longFacNames = lfac
                 # , longIndNames = lind
                 )
    configural <- "thresholds"; metric <- c(configural, "loadings")
    scalar <- c(metric, "intercepts"); strict <- c(scalar, "residuals")
    mods <- list()
    args$long.equal = configural; 
    mods$configural <- do.call(measEq.syntax, args)
    args$long.equal = metric; 
    mods$metric <-  do.call(measEq.syntax, args)
    args$long.equal = scalar; 
    mods$scalar <-  do.call(measEq.syntax, args)
    args$long.equal = strict; 
    mods$strict <- do.call(measEq.syntax, args)
    return(mods)
}
```

```{r, eval = F}
minv_nested_3 <- nested_data %>%
  filter(study %in% c("LISS", "SHARE", "ELSA", "HRS")) %>% #
  mutate(minv_mods = map(data, mi_fun))
```

```{r, eval = F}
MI_extract_fun <- function(mods){
  ldply(mods, fitmeasures) %>%
    select(.id, df, aic, bic, cfi, rmsea, srmr) %>% 
    mutate_at(vars(cfi, rmsea, srmr), list(delta = 
      ~ifelse(.id == "metric", .[.id == "configural"] - .[.id == "metric"],
      ifelse(.id == "scalar", .[.id == "metric"] - .[.id == "scalar"],
      ifelse(.id == "strict", .[.id == "scalar"] - .[.id == "strict"], NA))))) %>%
    bind_cols(
      rbind(
         rep(NA,3),
         (anova(mods$configural, mods$metric) %>% data.frame)[2,c("Chisq.diff", "Df.diff", "Pr..Chisq.")],
         (anova(mods$metric,     mods$scalar) %>% data.frame)[2,c("Chisq.diff", "Df.diff", "Pr..Chisq.")],
         (anova(mods$scalar,     mods$strict) %>% data.frame)[2,c("Chisq.diff", "Df.diff", "Pr..Chisq.")]
      ) %>% setNames(c("delta_Chisq", "delta_df", "p_Chisq"))
    )
}

minv_nested_3 <- minv_nested_3 %>%
  mutate(res = map(minv_mods, MI_extract_fun))
save(minv_nested_3, file = sprintf("%s/03-results/12-meas-inv/meas_inv.RData", wd))
minv_nested_3 <- minv_nested_3 %>% select(study, res)
save(minv_nested_3, file = sprintf("%s/03-results/12-meas-inv/meas_inv_small.RData", wd))
```

```{r}
load(sprintf("%s/results/meas_inv_small.RData", local_path))
comb <- paste(rep(traits$old, each = 3),
              rep(c("cfi", "rmsea", "srmr"), times = 4), sep = ".") 

tab <- minv_nested_3 %>% 
  select(study, res) %>%
  unnest(res) %>%
  mutate_at(vars(aic:cfi, delta_Chisq), ~sprintf("%.2f", .)) %>%
  mutate_at(vars(rmsea, srmr, cfi_delta, rmsea_delta, srmr_delta)
            , ~ifelse(abs(.) < .001, sprintf("%.4f", .), 
               ifelse(abs(.) < .01, sprintf("%.3f", .), sprintf("%.2f", .)))) %>%
  mutate_at(vars(p_Chisq), ~ifelse(. < .001, "< .001", ifelse(. < .01, "< .01", ifelse(. < .05, "< .05", "> .05")))) %>%
  mutate(study = factor(study, c("ELSA", "HRS", "SHARE", "LISS"))
         , .id = factor(str_to_title(.id), c("Configural", "Metric", "Scalar", "Strict"))) %>%
  arrange(study, .id) %>%
  select(.id, contains("df"), aic, bic, contains("cfi"), contains("rmsea"), contains("srmr"), contains("Chisq")) %>%
  # select(-study) %>%
  kable(.
        , "html"
        , col.names = c("Invariance", "df", "$\\Delta$ df", "AIC"
                        , "BIC", "CFI", "$\\Delta$ CFI", "RMSEA"
                        , "$\\Delta$ RMSEA", "SRMR", "$\\Delta$ SRMR"
                        , "$\\Delta \\chi^2$", "p")
        , caption = "<strong>Table SX</strong><br><em>Longitudinal Measurement Invariance Test for Multi-Item Measures</em>"
        , escape = F) %>%
  kable_classic(full_width = F, html_font = "Times New Roman") %>%
  kableExtra::group_rows("ELSA", 1, 4) %>%
  kableExtra::group_rows("HRS", 5, 8) %>%
  kableExtra::group_rows("SHARE", 9, 12) %>%
  kableExtra::group_rows("LISS", 13, 16) %>%
  footnote("ELSA, HRS, and SHARE include a three-item version of the UCLA Loneliness Scale. LISS includes the three-item De Jong Gierveld Loneliness Scale.")
save_kable(tab, file = sprintf("%s/03-results/10-tables/meas-inv-tab.html", wd))
tab
```

```{r}
cor_fun <- function(df){
  df2 <- df %>% select(-SID)
  df2 <- df2[,apply(df2, 2, function(x) sum(!is.na(x))/length(x) > .1)]
  r <- df2 %>%
    mutate(SID = df$SID) %>%
    pivot_wider(names_from = "year", values_from = "lonely") %>%
    # mutate_at(vars(-SID), rank) %>%
    select(-SID) %>%
    cor(., use = "pairwise")#, method = "spearman")
  
  coln <- colnames(r)
  # remove lower tri and diagonal
  r[lower.tri(r, diag = T)] <- NA
  r <- r %>% data.frame() %>%
    rownames_to_column("V1") %>%
    pivot_longer(
      cols = -V1
      , values_to = "r"
      , names_to = "V2"
    ) %>%
    mutate(V2 = str_remove(V2, "X")) %>%
    mutate_at(vars(V1, V2), ~factor(., coln))
}

heatmap_fun <- function(r, study){
  p <- r %>%
  ggplot(aes(x = V1, y = fct_rev(V2), fill = r)) + 
  geom_raster() + 
  geom_text(aes(label = round(r, 2))) + 
  scale_fill_gradient2(limits = c(-1,1)
    , breaks = c(-1, -.5, 0, .5, 1)
    , low = "blue", high = "red"
    , mid = "white", na.value = "white") + 
  labs(
    x = NULL
    , y = NULL
    , fill = "Zero-Order Correlation"
    , title = "Test-Retest Consistency Across Waves"
    , subtitle = study
    ) + 
  theme_classic() + 
  theme(
    legend.position = "bottom"
    , axis.text = element_text(face = "bold")
    , axis.text.x = element_text(angle = 45, hjust = 1)
    , plot.title = element_text(face = "bold", hjust = .5)
    , plot.subtitle = element_text(face = "italic", hjust = .5)
    , panel.background = element_rect(color = "black", size = 1)
  )
  ggsave(p, file = sprintf("%s/03-results/09-plots/04-test-retest-cor/%s.png", wd, study)
         , width = 8, height = 9)
  ggsave(p, file = sprintf("%s/03-results/09-plots/04-test-retest-cor/%s.pdf", wd, study)
         , width = 8, height = 9)
  return(p)
}

nested_test_retest <- nested_data %>%
  filter(study %in% c("SHP", "GSOEP", "SATSA", "HILDA", "OCTOTWIN")) %>%
  mutate(r = map(data, cor_fun)
         , p = map2(r, study, heatmap_fun))
```


